<?php
!function_exists('readover') && exit('Forbidden');
$search = array(
	'basic'	=> array(
		'action=state'	=> array(
			'name' => '站点状态',
			'setting_state_set' => '站点状态设置',
			'setting_bbsifopen' => '站点状态:<br />完全开放：允许任何人访问站点。<br />内部开放：特定会员才能访问站点，通常用于站点内部测试、调试。<br />完全关闭：除站点创始人，其他人都不允许访问站点，一般用于站点关闭、系统维护等情况。',
			'setting_bbsifopen_0' => '完全关闭',
			'setting_bbsifopen_1' => '完全开放',
			'setting_bbsifopen_2' => '内部开放',
			'setting_visitopen' => '是否只允许特定会员或特定用户组访问：<br />关闭则表示允许所有已注册会员访问站点。<br />开启则表示只允许特定会员及特定用户组访问站点，需进一步设置允许访问的特定用户组和特定会员。<br />特定用户组和特定会员可以单独设置，亦可同时设置，同时留空效果等同于完全关闭。',
			'setting_visitgroup' => '内部特定用户组：<br />在内部状态下，只允许特定用户组访问站点，留空则表示不使用此功能。',
			'setting_visituser' => '内部特定会员：<br />在内部状态下，除特定用户组外，允许访问站点的特定会员，留空则表示不使用此功能，会员用户名请用英文逗号“,”分隔。',
			'setting_visitmsg' => '内部开放提示信息：<br />当站点状态选择为内部开放状态下提示的信息。',
			'setting_whybbsclose' => '关闭状态信息：<br />当站点状态选择为完全关闭状态下提示的信息。',
			'setting_openpost' => '定时发帖功能：<br />定时打开与关闭发帖功能，设置用户可以使用发帖功能的时间段(24小时制)，支持跨越零点搜索，管理员与总版主不受此限制<br />例如：用户在 每晚20:00 到 次日8:00 这段时间内可以使用发帖，发帖开启于(点)设为：20；发帖关闭于(点)设为：8。',
			'setting_poststart' => '发帖开启于(点)：',
			'setting_postend' => '发帖关闭于(点)：',
			'setting_opensch' => '定时搜索功能：<br />定时打开与关闭搜索功能，设置用户可以使用搜索功能的时间段(24小时制)，支持跨越零点搜索，管理员与总版主不受此限制<br />例如：用户在 每晚22:00 到 次日10:00 这段时间内可以使用搜索，搜索开启于(点)设为：22；搜索关闭于(点)设为：10。',
			'setting_schstart' => '搜索开启于(点)：',
			'setting_schend' => '搜索关闭于(点)：',
		),
		'action=info'	=> array(
			'name' => '站点信息',
			'setting_bbsset' => '站点信息设置',
			'setting_bbsname' => '站点名称：<br />填写您站点的名称。',
			'setting_bbsurl' => '站点地址：<br />填写您站点的地址，输入的时候请包括完整的域名。',
			'setting_ceoconnect' => '联系链接：<br />填写联系站点管理员的链接地址，可以是邮件(比如: mailto:webmaster@phpwind.net) 或其他链接。出现在每页底部。',
			'setting_ceoemail' => '管理员邮箱：<br />填写站点管理员的邮箱地址。',
			'setting_icp' => 'ICP 备案信息：<br />填写 ICP 备案的信息',
		),
		'action=global'	=> array(
			'name' => '全局参数设置',
			'setting_defaultstyle' => '站点默认风格：<br />选择站点的默认风格。用户在没有指定风格的时候，均使用默认风格。',
			'setting_columns' => '是否开启左右分栏：<br />左右分栏的开关，开启后可选择分栏的默认模式。',
			'setting_columns_0' => '关闭左右分栏',
			'setting_columns_1' => '开启，默认使用平板模式',
			'setting_columns_2' => '开启，默认使用分栏模式',
			'setting_charset' => '站点默认编码：<br />选择与您使用的站点编码相同的设置，如无需要请不能随意更改。',
			'setting_charset_g' => '简体中文 (gbk)',
			'setting_charset_u' => 'UTF8编码 (utf-8)',
			'setting_charset_b' => '繁体中文 (big5)',
			'setting_forcecharset' => '强制设置编码：<br />解决国外的空间乱码问题，如无需要请不能随意更改。',
			'setting_timedf' => '站点默认时区：<br />游客和新用户的默认时区时间显示，会员可通过用户中心设置自己的时区。',
			'setting_cvtime' => '服务器时间校正：[分钟]<br />在您设置好服务器时区后，时间显示仍有错误，或想对服务器时间进行细调，请使用此功能进行修改。',
			'setting_datefm' => '默认时间显示格式：<br />格式如:yyyy-mm-dd，yy-m-d<br />yyyy代表4位数年份，yy代表2位数年份。<br />mm代表有前导零01-12，m代表没前导零1-12。<br />dd代表有前导零01-31，d代表没前导零1-31。',
			'setting_datefm_24' => '24小时制',
			'setting_datefm_12' => '12小时制',
			'setting_maxresult' => '搜索返回的最大结果数：<br />搜索结果只返回设置数值的结果数，如果超过这个数值，超过的部分将被抛弃。',
			'setting_schwait' => '搜索间隔时间：[秒]<br />用户进行一次搜索后，再次进行搜索所需要等待的时间。设置为0则用户随时都可以搜索。',
			'setting_msgsound' => '是否开启短信息声音提示：<br />打开后，如果发现有新的短信息，则会播放提示声音。',
			'setting_txtadnum' => '显示在页面头部的广告每行显示条数：',
			'setting_maxmember' => '用户列表最大页数：<br />用户列表中用户可以查看的最大页数，建议设置为 1000 －2500 之间，0或留空表示不限制。',
			'setting_adminset' => '是否开启副版主功能：<br />开启该功能，第一版主有权任命和罢免其他版主。',
			'setting_menu' => '弹出式菜单显示：<br />头部导航(头部导航弹出下拉菜单显示分类，如：统计排行)；版块导航(帖子列表页面、发帖页面弹出下拉菜单显示版块)；个人信息(帖子阅读页面弹出菜单用户资料)。',
			'setting_menu_0' => '头部导航',
			'setting_menu_1' => '版块导航',
			'setting_menu_2' => '个人信息',
			'setting_ajax' => 'AJAX 使用控制：<br />主题管理操作(置顶，加亮，提前等)；回复管理操作(删除，禁言，屏蔽等)<br />快捷发帖(引用，编辑)；回复其他操作(评分，推荐，报告等)；首页登录。',
			'setting_ajax_0' => '主题管理操作',
			'setting_ajax_1' => '回复管理操作',
			'setting_ajax_2' => '快捷发帖',
			'setting_ajax_3' => '回复其他操作',
			'setting_ajax_4' => '首页登录',
			'setting_ifjump' => '是否使用自动跳转：<br />如果服务器为NT，关闭此选项时出现无法登录状况，请开启。',
			'setting_refreshtime' => '刷新时间间隔：<br />您可以开启此功能以阻止用户恶意刷新。启用此限制后，刷新页面必须间隔一定的时间。设置为0则不作限制。',
			'setting_enterreason' => '强制输入操作原因：<br />为了避免由于管理操作上的不透明而引起站点会员纠纷，管理员可启用此项功能，强制要求在前台进行管理操作时输入操作原因。',
			'setting_adminreason' => '备选操作原因:<br />显示于前台管理操作原因备选框中。每行填写一个操作原因，空行表示分隔符“-------”。',
			'setting_onlinetime' => '在线用户时限：[分钟]<br />如果用户在这段时间，没有点击站点的任何链接，他的会话便会超时。同时，其用户名会从在线用户列表中删除。',
			'setting_today' => '统计今日到访会员：<br />大型站点建议关闭，影响速度。',
			'setting_recycle' => '站点回收站功能：<br />关闭回收站功能，删除主题回复时将进行直接删除操作。',
			'setting_footertime' => '是否在页脚显示程序运行时间：',
			'setting_debug' => 'DEBUG 模式运行站点：<br />显示程序错误报告信息，站点出现异常时打开此模式，再将错误信息提交给程序开发商，以便尽快得到解决。',
			'setting_forumdir' => '二级目录/域名功能：<br />以二级目录/域名访问方式，功能介绍参照程序包中的“分站点二级域名(目录)功能.txt”文档。',
			'setting_forumdir_0' => '不使用',
			'setting_forumdir_1' => '直接访问',
			'setting_forumdir_2' => '二级域名访问',
			'setting_ckpath' => 'Cookie 路径：<br />一般情况下，请填写“/”，如果您在同一个域名下运行了多个站点，便需要将它设置为每个站点所在的目录名以防冲突。如“/bbs/”、“/forum/”。<br />注意：只有在特殊情况下才需要进行此设置，若您不能肯定，请填写“/”，输入错误的设置会导致您无法登录站点。',
			'setting_ckdomain' => 'Cookie 作用域：<br />一般情况下，请留空，如果您的站点有两个不同的网址，如“phpwind.net”、“bbs.phpwind.net”，要使用户在两个不同的域名访问下，仍然能保持登录状态，您需要在设置为“.phpwind.net” (注意域名需要以点开头)。<br />注意：只有在特殊情况下才需要进行此设置，若您不能肯定，请留空，输入错误的设置会导致您无法登录站点。',
			'setting_toolbar' => '站点底部快捷栏：<br />是否显示站点底部快捷栏',
		),
	),
	'safe'	=> array(
		'action=speed'	=> array(
			'name' => '速度优化',
			'setting_cls_speed_set' => '速度优化设置',
			'setting_lp' => '进程优化：<br />建议15分钟在线1000人以上站点打开此选项。',
			'setting_onlinelmt' => '最大在线人数：<br />当站点在线人数达到填写的数值时提示错误，留空或0为无限制。',
			'setting_online' => '站点在线会员(游客)算法：',
			'setting_online_0' => '文本在线',
			'setting_online_1' => '数据库在线',
			'setting_obstart' => 'GZIP 压缩级别：<br />设置 GZIP 在输出时的压缩级别: 0=关闭GZIP功能，9=最大压缩比。<br />如果您已经在服务器上使用了mod_gzip 或者 mod_deflate，请设置为0关闭GZIP功能，否则强烈推荐使用级别 1。另外，此功能要求 ZLIB 库支持。<br />GZIP 压缩输出简介：使用 GZIP HTML 压缩输出给用户页面，这会减少带宽要求。此功能要求客户端浏览器的支持，以及 HTTP 1.1 兼容。它会产生服务器额外的性能开销。',
			'setting_redundancy' => '清除页面冗余内容：',
		),
		'action=seo'	=> array(
			'name' => '搜索引擎优化',
			'setting_cls_seo_set' => '搜索引擎优化设置(SEO)',
			'setting_bbstitle' => 'Title 描述：<br />为首页或其他页面输入站点的标题(title)描述，让搜索引擎更容易找到您的站点。<br />例如：PHPWind 官方论坛',
			'setting_indextitle' => '首页的描述：',
			'setting_othertitle' => '其他页面的描述：',
			'setting_metakeyword' => 'Meta 关键词：<br />为所有页面输入 Meta 关键词，让搜索引擎更容易找到您的站点。<br />例如：php,免费,论坛,系统,bbs,mysql,下载',
			'setting_metadescrip' => 'Meta 描述：<br />为所有页面输入 Meta 描述，以便能够在搜索引擎中正确搜索到您的站点。<br />例如：PHPWind 论坛系统是一套安全、高负载、可扩展、易用等特性的开源软件系统。',
		),
		'action=gdcode'	=> array(
			'name' => '验证机制',
			'setting_cls_gdcode_set' => '认证码设置',
			'setting_gdcheck' => '开启认证码：',
			'setting_gdcheck_0' => '注册',
			'setting_gdcheck_1' => '前台登录',
			'setting_gdcheck_3' => '短消息',
			'setting_gdcheck_5' => '后台登录',
			'setting_postgd' => '发帖验证码限制：<br />设置100，则发帖数小于100的会员，将显示验证码;设置0 则关闭该功能。',
			'setting_gdstyle' => '图象验证的识别难度：<br />注：由于部分服务器对字体和gif功能支持不友好，如果您的站点开启认证码后出现服务器不稳定现象请关闭“随机字体”，“中文验证码”与“gif动画”这几个选项。',
			'setting_gdstyle_0' => '随机字体',
			'setting_gdstyle_1' => '随机字体大小',
			'setting_gdstyle_2' => '随机倾斜',
			'setting_gdstyle_3' => '随机背景',
			'setting_gdstyle_4' => '随机颜色',
			'setting_gdstyle_5' => '随机干扰图形',
			'setting_gdstyle_6' => 'gif动画',
			'setting_gdtype' => '验证码类型：',
			'setting_gdtype_0' => '数字验证码',
			'setting_gdtype_1' => '英文验证码',
			'setting_gdtype_2' => '中文验证码',
			'setting_gdtype_3' => '随机',
			'setting_gdsize' => '验证码尺寸：<br />尺寸请不要超过 200 * 80。',
			'setting_gdsize_2' => '个数：',
			'setting_cls_gdcode_set' => '验证码设置',
			'setting_cls_question_set' => '验证问题设置',
			'setting_qcheck' => '验证问题与答案：<br />1、您可以使用简单的文字问题(例如：3+5=?，请输入中文答案)<br /> 2、也可以使用html代码(例如将问题做成一张小图片 &lt;img src="地址" /&gt;)<br />3、多个问题将随机出现一个问题。',
			'setting_add' => '添加',
			'setting_answer' => '答案',
			'setting_regq' => '注册验证问题功能：',
			'setting_loginq' => '前台登录验证问题功能：',
			'setting_postq' => '发帖验证问题功能：<br />设置100，则发帖数小于100的会员，将显示验证问题;设置 0 则关闭该功能。',
			'setting_msgq' => '短消息验证问题功能：',
		),
		'action=dir'	=> array(
			'name' => '动态目录',
			'setting_cls_dir_set' => '动态目录设置',
			'setting_picpath' => '图片保存目录：<br />如果设置绝对路径，必须为空间上的目录。如果发现不可更改，请确认目录可写入。目录分隔符请使用“/”不要使用“\”。',
			'setting_attachname' => '附件保存目录：<br />如果设置绝对路径，必须为空间上的目录。如果发现不可更改，请确认目录可写入。目录分隔符请使用“/”不要使用“\”。',
			'setting_htmdir' => '静态HTML文件保存目录：<br />如果设置绝对路径，必须为空间上的目录。如果发现不可更改，请确认目录可写入。目录分隔符请使用“/”不要使用“\”。',
			'setting_autochange' => '自动不定期更改图片链：<br />小型站点不推荐选开启。',
			'setting_hour' => '定时更改图片目录防止图片盗链：[小时]<br />如果上一选项选否，此项无效。',
			'setting_http' => '使用跨台固定图片链：<br />不使用请写“N”，小型站点不推荐使用，请不要随意更改。',
			'setting_attachurl' => '远程附件连接设置：<br />不使用请写“N”，请不要随意更改。',
		),
		'action=safe'	=> array(
			'name' => '安全控制',
			'setting_cls_safe_set' => '安全控制设置',
			'setting_loadavg' => '系统负载控制参数：<br />当服务器的负载参数大于这个值时，自动开启CC防护模式，建议设置为 3。',
			'setting_cc' => 'CC攻击防护：<br />不 使 用：关闭CC攻击防护。<br />普通模式：建议使用这种模式，可预防站点遭受cc攻击。<br />加强模式：当网站正遭受CC攻击而导致访问速度很慢时，请开启此种模式可阻止攻击。',
			'setting_cc_0' => '不使用',
			'setting_cc_1' => '普通模式',
			'setting_cc_2' => '加强模式',
			'setting_ifsafecv' => '安全问题功能：<br />如果会员设置了安全问题，需要填写正确的答案才能登录站点，可提高密码安全性。',
			'setting_safegroup' => '强制使用安全问题用户组设置：<br />可以强制管理权限较高的用户组(如：管理员,总版主,版主)使用安全问题，可提高密码安全性。',
			'setting_registerfile' => '修改用户注册文件文件名：',
			'setting_adminfile' => '修改后台登录文件文件名：',
			'setting_xforwardip' => '内部网IP匹配：<br />如果打开，将检查 X_FORWARDED_FOR 头信息来匹配用户的 IP 地址。<br />本功能应用在企业内部网或服务器开启反向代理等环境下。',
			'setting_ipcheck' => 'IP验证功能：<br />可以加强站点安全，选择开启将对登录者ip进行验证<br />如果与上一次登录ip前2位不同，将要求重新登录。',
			'setting_iplimit' => '后台登录IP限制：<br />此功能可绑定登录后台的 IP，只有在列表内的 IP 才能登录站点，创始人不受限制<br>可以绑定单个IP地址格式如：192.0.0.1，也可以绑定一段IP格式如：192.0.0<br>多个IP "," 分隔。',
			'setting_hash' => '站点安全验证参数：<br />除非站点出现安全危机，请不要随意修改。',
		),
	),
	'att'	=> array(
		'action=att'	=> array(
			'name' => '附件设置',
			'setting_cls_att_set' => '附件基本设置',
			'setting_allowupload' => '是否开启附件上传功能：',
			'setting_attachdir' => '附件保存方式：<br />如果使用非默认的保存方式，请确认 mkdir() 函数可正常使用，否则设置后新上传的附件无法保存，更改不影响已上传附件。',
			'setting_attachdir_0' => '全部存入同一目录(默认)',
			'setting_attachdir_1' => '按版块存入不同目录',
			'setting_attachdir_2' => '按类型存入不同目录',
			'setting_attachdir_3' => '按月份存入不同目录',
			'setting_attachdir_4' => '按天存入不同目录',
			'setting_attachhide' => '附件大于多少时使用真实路径下载：[KB]<br />当附件比较大时，可减少php进程消耗；当使用远程附件时，可转移流量、减轻服务器负担。留空或0为关闭此功能。',
			'setting_attachnum' => '一次最多上传附件个数：',
			'setting_maxuploadsize' => '上传附件允许后缀和最大尺寸：[KB]<br />系统限制上传附件最大尺寸：。',
		),
		'action=watermark'	=> array(
			'name' => '图片水印',
			'setting_watermark' => '是否使用图片水印功能：<br />将在站点上传的图片附件中加上您在下面设置的图片或文字水印。（同时在版块基本权限里开启方可使用</blue>）',
			'setting_ifgif' => '是否为 gif 格式图片加水印：<br />由于 GD 库函数存在漏洞，请选择以下选项为gif格式图片加水印。<br />强制：程序将不对 PHP 版本做判断，强制加水印。<br />开启：判断 PHP 版本,版本符合，则加水印。<br />关闭：关闭水印功能。<br />不影响的 PHP 版本(4.4.3、4.4.4、5.1.5 以上)。',
			'setting_ifgif_2' => '强制开启',
			'setting_water' => '添加水印的图片大小控制：<br />只对超过程序设置的大小的附件图片才加上水印图片或文字。留空或0为无限制。',
			'setting_waterwidth' => '宽：',
			'setting_waterheight' => '高：',
			'setting_waterpos' => '水印位置：',
			'setting_waterpos_0' => '随机位置',
			'setting_waterpos_1' => '顶部居左',
			'setting_waterpos_2' => '顶部居中',
			'setting_waterpos_3' => '顶部居右',
			'setting_waterpos_4' => '底部居左',
			'setting_waterpos_5' => '底部居中',
			'setting_waterpos_6' => '底部居右',
			'setting_waterpos_7' => '中心位置',
			'setting_waterimg' => '水印图片文件名：<br />水印图片存放路径：，如果水印图片不存在，则使用文字水印。',
			'setting_watertext' => '水印图片文字：',
			'setting_waterfonts' => "文字水印字体选择：<br />字体必须为'.ttf'后辍文件，上传 字体到以下路径<br>英文字体目录:<br />中文字体目录:",
			'setting_fonteng' => '英文字体',
			'setting_fontch' => '中文字体',
			'setting_waterfont' => '水印图片文字字体大小：',
			'setting_watercolor' => '水印图片文字颜色：<br />十六进制颜色值，默认为#FF0000(红色)。',
			'setting_waterpct' => '水印透明度：<br />决定图片水印清晰度，其值范围从 0 到 100。',
			'setting_jpgquality' => '图片质量：<br />决定 jpg 格式图片的质量，其值范围从 0 到 100。',
		),
		'action=ifathumb'	=> array(
			'name' => '图片缩略',
			'setting_ifathumb' => '是否使用附件缩略图功能：<br />站点上的图片附件，按照一定比例，缩略成一张清晰的图片。',
			'setting_athumb' => '附件缩略图宽高控制：<br />只对超过宽高控制的图片才进行缩略。留空或0为不缩略图片。',
		),
		'action=ftp'	=> array(
			'name' => 'FTP设置',
			'setting_ifftp' => '是否使用FTP方式上传：<br />本功能适合上传附件到远程服务器，尤其针对镜像站点，可将附件传至主站点，便于附件的统一管理。',
			'setting_ftpweb' => '站点附件地址:<br />例如：http://www.phpwind.net/attachment。',
			'setting_server' => 'FTP服务器地址：',
			'setting_port' => 'FTP服务器端口：',
			'setting_dir' => 'FTP上传目录：<br />请确保该目录等同于主站点的attachment目录。',
			'setting_user' => 'FTP帐号：',
			'setting_pass' => 'FTP密码：',
			'setting_timeout' => 'FTP超时：[秒]<br />系统将在这个时间内等待服务器的响应。',
		),
	),
	'attachment'	=> array(
		'attachment_info' => '为了保证空间的可持续发展,请及时清理!附件保存目录为:<br>功能说明: 本功能根据数据库中的附件记录搜索,  删除符合条件的附件和附件记录, 释放更多的数据库空间和服务器空间<br>',
		'attachment_title' => '附件编辑',
		'attachment_filename' => '文件名包含',
		'attachment_hits' => '下载次数',
		'attachment_less' => '小于',
		'attachment_more' => '大于',
		'attachment_size' => '附件大小',
		'attachment_time' =>'上传时间',
		'attachment_order' => '排序',
		'attachment_name' => '附件名',
		'attachment_schnum' => '每页显示个数',
		'attachment_direct'=>'直接删除符合条件的附件',
		'attachment_schdir'=>'功能说明:本功能可根据附件最后被访问时间搜索整个站点的附件, 选择删除长时间没人访问的附件, 可有效清理站点中冗余附件, 从而释放更多的服务器空间.<br>注:如果你要删除的附件比较多,可以使用直接删除功能, 直接删除符合搜索条件的附件',
		'attachment_viewold'=>'查看上次搜索结果',
		'attachment_visit'=>'最后访问时间',
		'attachment_pernum'=>'每次跳转处理个数',
		'attachment_delfile'	=> '本功能将搜索整个站点的附件，删除数据库中没有记录而实际存在的附件，可有效清理站点中冗余附件, 从而释放更多的服务器空间.',
		'attachment_del_msg'=>'删除个数',
		'attachment_noexists'=>'已删',
		'attachment_list' => '站点附件',
		'attachment_topic'=>'所在主题',
	),
	'attachrenew'	=> array(
		'attachrenew_area' => '查错范围',
		'attachrenew_order' => '排序',
		'attachrenew_size' => '附件大小',
		'attachrenew_id' => '附件ID',
		'attachrenew_search' => '查找',
		'attachrenew_title' => '附件手动修复(附件不存在而附件记录存在)--- 使用 ftp 远程转移附件功能.此管理无效',
		'attachrenew_name' => '附件名称',
		'attachrenew_url' => '附件链接',
		'attachrenew_auto' => '附件自动修复',
		'attachrenew_auto_info' => '当附件记录大于 1 万时。强烈建议使用上面手动搜索的功能,不要使用此具负载性的功能!<br>本功能清除只存在附件记录而没有附件的冗余数据，帖子中的附件记录也将同时更新<br>使用 ftp 远程转移附件功能.此管理无效',
	),
	'attachstats'	=> array(
		'attachstats_guide' => '附件统计',
		'attachstats_sum' => '附件总计(个)',
		'attachstats_space' => '附件占用空间(KB)',
		'attachstats_average' => '附件平均大小(KB)',
		'attachstats_hits' => '总计下载次数(次)',
		'attachstats_hot' => '前二十个最热门附件',
		'attachstats_id' => '附件ID',
		'attachstats_name' => '附件名称',
		'attachstats_down' => '附件下载',
		'attachstats_size' => '附件大小',
		'attachstats_times' => '下载次数',
		'attachstats_forum' => '所在版块',
		'attachstats_most' => '前二十个最大附件',
	),
	'credit'	=> array(
		'action=name'	=> array(
			'name'	=> '积分名称设置',
			'setting_credit_type' => '积分类型',
			'setting_credit_unit' => '积分单位',
			'setting_moneyname'	=> '货币',
			'setting_rvrcname'=> '威望',
			'setting_creditname'=> '贡献值',
			'setting_currencyname'=> '交易币',
		),
		'action=prize'	=> array(
			'name' => '帖子奖惩选项',
			'setting_digest'=>'精华主题',
			'setting_post'=>'发表主题',
			'setting_reply'=>'发表回复',
			'setting_undigest'=>'取消精华',
			'setting_delete'=>'删除主题',
			'setting_deleterp'=>'删除回复',
			'setting_atcset_warn' => '注：威望积分设置支持1位小数点，其他积分只允许整数！',
		),
		'action=pass'	=> array(
			'name' => '积分流通记录',
			'setting_info_flow' => '此功能可以详细记录某种积分的流通情况，帮助站长更加清晰地掌握站点的积分状况！',
			'setting_atc' => '帖子奖惩',
			'setting_mark' => '评分',
			'setting_reward' => '悬赏',
			'setting_hack' => '插件相关',
		),
		'action=supple'	=> array(
			'name' => '充值积分设置',
			'setting_creditpay_info' => '充值积分设置：<br />转换比率：与人民币的汇率，通过支付￥1，获得的积分数量！',
			'setting_creditpay_rmbrate' => '转换比率',
			'setting_creditpay_rmblest' => '最少充值',
			'setting_creditpay_virement' => '允许转帐',
			'setting_virerate' => '转帐手续费比率：[%]',
		),
	),
	'creditdiy'	=> array(
		'credit_manage' => '自定义积分管理',
		'credit_add' => '添加自定义积分',
		'credit_guide' => '自定义积分',
		'credit_info' => '1.自定义积分将加入站点评分，积分排行榜<br>2.用户可以根据特定需要增加自定义积分',
		'credit_list' => '自定义积分列表',
		'credit_unit' => '单位',
		'credit_intro' => '说明',
		'credit_edit' => '编辑自定义积分',
		'credit_delete'=>'确定要删除自定义积分吗?删除自定义积分将同时删除会员该项积分数据!',
	),
	'creditchange'	=> array(
		'creditchange_guide' => '积分兑换公式',
		'creditchange_credit1' => '积分Ⅰ',
		'creditchange_credit2' => '积分Ⅱ',
		'creditchange_exchange' => '兑换',
		'creditchange_gongshi' => '添加兑换公式',
	),
	'reg'	=> array(
		'setting_reg_ctrl' => '用户注册控制',
		'setting_allowregister' => '允许新用户注册：<br />选择否将禁止游客注册成为会员，但不影响过去已注册的会员的使用。',
		'setting_whyregclose' => '关闭注册原因：',
		'setting_reg' => '注册时显示许可协议：<br />新用户注册时显示许可协议，同意后才能继续注册。',
		'setting_rgpermit' => '注册许可协议内容编辑：',
		'setting_regpopup' => '注册提示窗：<br />当访问站点的用户在还没有注册或未登录的情况下将弹出提示注册的窗口，登录和注册页面除外。',
		'setting_regdetail' => '注册时先显示注册协议的弹出框：<br />不开启将快速注册。',
		'setting_emailcheck' => '新用户注册需通过email激活用户：<br />选择“开启”将向用户注册 Email 发送一封验证邮件以确认邮箱的有效性，用户收到邮件并激活帐号后才能拥有正常的权限。',
		'setting_allowsameip' => '禁止同一IP在多少时间内不能重复注册：[小时]<br />0为不限制。',
		'setting_regsendemail' => '新用户注册发送电子邮件：<br />新用户注册后系统自动发送一封EMAIL。',
		'setting_regsendmsg' => '新用户注册发送短消息：<br />新用户注册后系统自动发送一条欢迎短消息。',
		'setting_welcomemsg' => '向新注册用户发送的欢迎短消息内容：',
		'setting_banname' => '禁止在注册用户名中使用的词语：<br />说明：如果你禁用了"版主"，那么所有含有"版主"(如：我是版主)的用户名将被禁止使用，多个词之间用","分隔。',
		'setting_email' => '限制注册用户仅能够使用某些邮箱进行注册：<br />如果您只使用163的邮箱，可以填写163.com，多个之间用","分开，不限制，请留空。<br />此功能可以帮助用户避免使用限制过多的邮箱服务器来收取站点信件。',
		'setting_ifcheck' => '新用户注册是否需要管理员在后台验证通过才能发帖：',
		'setting_rglower' => '注册会员ID不区分大小写：<br />建议默认: 关闭。',
		'setting_postallowtime' => '注册会员在多少时间内不能发表文章：[分钟]<br />0为不限制。',
		'setting_namelen' => '用户名长度：<br />用户名字符的最小和最大长度，最小值不能小于1，最大值不能大于15。',
		'setting_regminname' => '最小',
		'setting_regmaxname' => '最大',
		'setting_pwdlen' => '密码字符的最小和最大长度<br />最小值不能小于1。',
		'setting_regminpwd' => '最小',
		'setting_regmaxpwd' => '最大',
		'setting_npdifferf' => '不允许注册帐号与密码相同：',
		'setting_regcredit' => '注册时初始积分：',
		'setting_timestart' => '会员注册生日年限：<br />默认是1960-2000。',
		'setting_pwdcomplex' => '强制密码复杂度：<br />密码中必须存在所选字符类型，如果不选则为不限制。',
	),
	'member'	=> array(
		'action=post'	=> array(
			'name' => '信息发布',
			'setting_cls_post_set' => '信息发布设置',
			'setting_cvtimes' => '帖子中表情，动作以及 img，wmv，rm 等标签的最多转换次数：<br />建议设置为10 - 20 之间，-1 为不限制。',
			'setting_windpost_pic' => '帖子中 Wind IMG功能：',
			'setting_img_ctrl' => '帖子中[img]标签的大小控制：<br />留空不限制。',
			'setting_picwidth' => '宽：',
			'setting_picheight' => '高：',
			'setting_size_ctrl' => '帖子中[size]标签的大小控制：[最大值]<br />留空不限制。',
			'setting_flash' => '帖子中 Wind Flash功能：<br />建议关闭。',
			'setting_mpeg' => '帖子中 Wind (wmv,asf,ra,ram,rm)功能：',
			'setting_iframe' => '帖子中 iframe功能：',
			'setting_checkurl' => '帖子中检测外链功能：',
			'setting_windmagic' => '帖子中动漫传情功能：',
			'setting_tcheck' => '是否开启发帖内容验证：<br />开启该功能，会员将无法连续发表同一内容的主题。',
			'setting_titlemax' => '标题最大长度：',
			'setting_postmax' => '每篇文章的最大长度：[字节]',
			'setting_postmin' => '每篇文章的最小长度：[字节]',
			'setting_showreplynum' => 'post回复时显示提示旧帖数：',
			'setting_selcount' => '投票选项个数控制：',
			'setting_pwcode' => '编辑器是否开启自定义代码功能：',
			'setting_setform' => '编辑器是否开启帖子格式功能：',
			'setting_sellset' => '出售帖允许的积分类型：',
			'setting_allowsellset' => '出售帖允许的积分大小：',
			'setting_price' => '最高单价限制（0 为不限制）',
			'setting_income' => '最高收入限制（0 为不限制）',
			'setting_enhideset' => '加密帖允许的积分类型：',
			'setting_autoimg' => '是否使用自动贴图：',
			'setting_replysendmail' => '用户文章被回复是否发送邮件：',
			'setting_replysitemail' => '用户文章被回复是否发送站内通知：',
		),
		'action=face'	=> array(
			'name' => '头像签名设置',
			'setting_face_ctrl' => '头像宽高范围：',
			'setting_imgwidth' => '最大宽度',
			'setting_imglen' => '最大高度',
			'setting_ifupload' => '是否开启头像上传功能：<br />此处为全局控制，此功能关闭则所有用户都不能使用头像上传功能。',
			'setting_imgsize' => '最大尺寸(k)',
			'setting_iffthumb' => '是否使用头像缩略图功能：<br />站点上的头像，按照一定比例，缩略成一张清晰的图片。',
			'setting_fthumbsize' => '头像缩略图宽高控制：<br />只对超过宽高控制的图片才进行缩略，设置为0不缩略。',
			'setting_fthumbwidth' => '宽：',
			'setting_fthumbheight' => '高：',
			'setting_signheight' => '签名最大高度控制：',
			'setting_signwindcode' => '签名中 Wind 代码功能：',
			'setting_windpic_pic' => '签名中 Wind IMG功能：',
			'setting_windpic_img' => '签名中[img]标签的大小控制：<br />留空不限制。',
			'setting_picwidth' => '宽：',
			'setting_picheight' => '高：',
			'setting_windpic_size' => '签名中[size]标签的大小控制：[最大值]<br />留空不限制。',
			'setting_windpic_flash' => '签名中 Wind Flash功能：<br />建议关闭。',
			'setting_signmoney' => '签名显示一天需要相应积分数：<br />留空或设为‘0’不使用此功能。',
			'setting_signgroup' => '需要购买签名的用户组：<br />该功能配合phpwind-网上银行系统可为站长带来可观的经济来源。',
			'setting_logintype' => '设置用户登录方式：<br />不设置则只支持用户名登录。',
			'setting_selectgroup' => '是否允许更换用户组头衔：<br />拥有多个用户组头衔的会员有效。',
		),
	),
	'pcache'	=> array(
		'action=thread'	=> array(
			'name' => '主题列表内容缓存',
			'setting_cls_thread_set' => '主题列表内容缓存功能',
			'setting_cls_thread_info' => '主题列表内容缓存功能：<br />　　主题列表页是站点访问量最高的页面之一(尤其是前面几页)。',
			'setting_fcachenum' => '主题列表内容缓存页数：<br />设置 0 为关闭，建议值 10，即缓存前10页内容。',
			'setting_fcachetime' => '主题列表内容缓存更新间隔 ：[秒]<br />设置 0 为即时更新，即当有新帖发表时更新缓存内容<br />如果发帖较频繁，建议设置 180 - 300，即 3-5 分钟更新一次缓存内容',
			'setting_cls_guest_set' => '游客缓存功能',
			'setting_cls_guest_info' => '游客缓存功能：<br />　　一般情况下站点的在线用户70%以上为游客，而游客访问的页面内容在一段时间内是不会有太大变化的，因此将游客访问的页面内容缓存起来可以减少数据库因查询大量相同信息而产生的不必要的资源消耗。',
			'setting_guestdir' => '缓存目录：<br />默认为 data/guestcache 目录，您可以更改为其他目录，请确定您指定的目录有可写权限。',
		),
		'action=guest'	=> array(
			'name' => '游客缓存',
			'setting_guestindex' => '首页游客缓存设置：[秒]<br />设置首页缓存更新时间，0为关闭，建议值：900。',
			'setting_fguestnum' => '主题列表页面游客缓存页数：<br />设置 0 为关闭，建议值 10，即缓存前10页内容。',
			'setting_guestthread' => '主题列表页面游客缓存设置：[秒]<br />设置主题列表页面缓存更新时间，建议值：600。',
			'setting_tguestnum' => '帖子页面游客缓存页数：<br />开启此功能，将产生大量缓存数据，设置 0 为关闭，建议值 3，即缓存前3页内容。',
			'setting_guestread' => '帖子页面游客缓存设置：[秒]<br />设置阅读帖子页面缓存更新时间，建议值：900。',
		),
	),
	'index'	=> array(
		'setting_indexset' => '首页细节设置',
		'setting_setindex' => '站点默认首页：<br />当地址栏里没有指定访问哪个页面时，默认指向的页面。',
		'setting_bfn' => '站点首页调用文件：',
		'setting_todaypost' => '是否显示 今日昨日发帖数 与 版块今日发帖数：',
		'setting_indexfmlogo' => '自定义首页各版块的图片logo：<br />使用默认：将图标命名为*.gif（*表示对应的版块ID）,上传至images\***\ forumlogo（*代表风格目录名称）即可 <br />使用自定义：在版块设置里上传图片或填写图片地址即可',
		'setting_indexfmlogo_0' => '不使用',
		'setting_indexfmlogo_1' => '默认',
		'setting_indexfmlogo_2' => '自定义',
		'setting_adminshow' => '下拉框方式显示版主：',
		'setting_indexshowbirth' => '首页显示今天生日会员：<br />如果选择“开启”，将在站点首页显示今天过生日的会员。',
		'setting_bdayautohide' => '当没有会员过生日时自动隐藏：<br />如果选择“开启”，没有人过生日的时候站点首页将自动隐藏今日生日模块。',
		'setting_indexlink' => '是否显示友情链接：',
		'setting_indexmqshare' => '是否滚动显示友情链接：',
		'setting_ifselfshare' => '是否开启自助友情链接：<br />会员可在前台自助申请友情链接（每个会员只能申请一次），管理员审核通过后在前台显示。',
		'setting_usergroup' => '选择参与在线显示的用户组：<br />被选择的用户组将参与在线显示，在复选框内填写用户组显示顺序。<br />在线图标以用户组ID命名。<br />注：参与在线显示的用户组图标必须存在否则无法正常显示<br />&nbsp;&nbsp;&nbsp;&nbsp;如管理员ID为3，在线图标为 3.gif。',
		'setting_indexonline' => '首页显示在线用户：<br />影响速度。',
		'setting_showguest' => '首页显示在线游客：<br />影响速度。',
	),
	'thread'	=> array(
		'setting_threadset' => '主题列表细节设置',
		'setting_newtime' => '分版块主题多少时间表示为新帖：[秒]',
		'setting_perpage' => '站点主题列表每页显示主题数：',
		'setting_maxpage' => '主题列表最大显示页数：<br />主题列表中用户可以查看的最大页数，建议设置为 1000 －2500 之间，0 为不限制。',
		'setting_maxtypenum' => '主题列表页主题分类默认显示个数：',
		'setting_hithour' => '点击率延迟更新功能：[小时]<br />设置为0则不使用此功能,使用生成html功能将自动使用此功能。',
		'setting_topped' => '总置顶, 分类置顶功能：<br />置顶3: 为总置顶。置顶2: 为分类置顶。置顶1:为本版块置顶。',
		'setting_threadonline' => '版块内显示在线用户：',
		'setting_threademotion' => '各分版块帖子导航里显示表情符：',
		'setting_threadshowpost' => '各分版块帖子里显示快速发表主题：',
	),
	'read'	=> array(
		'setting_readset' => '帖子阅读页面细节设置',
		'setting_readperpage' => '阅读一主题时每页显示帖子数：',
		'setting_anonymousname' => '匿名的名称：<br />发表匿名帖时,用户显示的昵称',
		'setting_showonline' => '阅读帖子时显示在线用户：',
		'setting_showcolony' => '是否在帖子页面显示用户加入的群组：',
		'setting_showcustom' => '选择要在帖子阅读页面（read.php）显示的自定义积分：',
		'setting_pingtime' => '评分时间限制：[小时]<br />帖子发表后超过此时间限制其他用户将不能对此帖评分，系统组不受限制，0 为不限制。',
		'setting_ipfrom' => '浏览帖子处显示会员IP来源：<br />用户权限中可单独设置每个用户组权限，此处关闭则所有用户组都不能查看IP来源。',
		'setting_shield' => '是否开启屏蔽禁言会员所有帖子：',
		'setting_ifonlinetime' => '是否记录会员在线时间并在版块内显示：',
		'setting_floorunit' => '帖子楼层单位<br />设置帖子显示楼层的单位，如“楼”将显示为 1 楼',
		'setting_floorname' => '帖子楼层名称<br />格式 “楼层名称”或“N:楼层名称”，N代表楼层数（主题帖为0楼），如果没有指定楼层N，则第一行代表主题帖子。其中，连续楼层之间可以用‘，’逗号隔开或换行，N后面的楼层为N+1，以此类推，直到再次出现N。例：<br />0:楼主，沙发，板凳<br />3:地板，地下室<br />100:中奖楼层<br />',
	),
	'jsinvoke'	=> array(
		'setting_cls_js_set' => 'JS调用设置',
		'setting_jsifopen' => '是否开启 JS调用：<br />此功能允许在您的网站首页或其他地方调用站点的内容。<br />调用方式分为： 版块调用、公告调用、基本信息调用、会员排行调用、文章调用。',
		'setting_jsper' => '缓存更新时间：[秒]<br />由于部分调用查询比较消耗服务器资源，系统采用了缓存技术实现数据定期更新。<br />建议设置为：900。',
		'setting_bindurl' => '允许调用网站域名：<br />您可以设置允许调用站点内容的网站域名列表，只有在列表中的域名才能调用站点信息。<br />多个域名用 "," 分隔域名，不要包含 http:// 或其他非域名内容，留空不限制。',
	),
	'popinfo'	=> array(
		'setting_sitemsg' => '重要页面弹出信息设置',
		'setting_sitemsg_reg' => '注册页面：<br>注册页面的弹出信息，每行填写一条信息，多条信息将随机显示。',
		'setting_sitemsg_login' => '登录页面：<br>登录页面的弹出信息，每行填写一条信息，多条信息将随机显示。',
		'setting_sitemsg_post' => '发贴页面：<br>发贴页面的弹出信息，每行填写一条信息，多条信息将随机显示。',
		'setting_sitemsg_reply' => '回复页面：<br>回复页面的弹出信息，每行填写一条信息，多条信息将随机显示。',
		'setting_ifcredit' => '是否开启积分变动提示：<br />开启后，当用户在站点积分变动时，将弹出信息通知用户。<br />请先到积分设置对积分流通记录进行设置。',
	),
	'email'	=> array(
		'action=email'	=> array(
			'name' => '邮件发送设置',
			'setting_mailifopen' => '是否开启发送邮件功能：',
			'setting_mailmethod' => '邮件发送模式：',
			'setting_mailmethod_1' => 'mail() 函数发送',
			'setting_mailmethod_2' => 'SMTP 模块发送',
			'setting_mailmethod_3' => 'MX 模块发送',
			'setting_smtp' => 'SMTP 模块发送设置',
			'setting_smtphost' => 'SMTP 服务器：',
			'setting_smtpport' => 'SMTP 端口：<br />默认不需修改。',
			'setting_smtpfrom' => '发信人地址：',
			'setting_smtpauth' => '是否需要 AUTH LOGIN 验证：<br />1=是，0=否。',
			'setting_smtpuser' => '验证用户名：',
			'setting_smtppass' => '验证密码：<br />安全考虑，只显示密码的前后两位，中间显示八个 * 号。',
			'setting_mx' => 'MX 模块发送设置',
			'setting_mxinfo' => '以 www.example.net 为例说明MX模块发送邮件设置<br />域名mx记录：mail.example.net (同时需要在域名控制面版里增加一条mx记录到 mail.example.net)<br />发送邮件帐号：admin@example.net<br />主DNS地址：可联系空间商查询您的服务器的DNS地址<br />辅DNS地址：可联系空间商查询您的服务器的DNS地址',
			'setting_smtphelo' => '域名mx记录：',
			'setting_smtpmxmailname' => '发送邮件帐号：',
			'setting_mxdns' => '主DNS地址：',
			'setting_mxdnsbak' => '辅DNS地址：',
		),
		'action=checkemail'	=> array(
			'name' => '邮件发送方式',
			'setting_email_function' => '函数发送',
			'setting_email_mod' => '模块发送',
			'setting_fromemail' => '发件人地址：',
			'setting_toemail' => '收件人地址：',
		),
	),
	'wap'	=> array(
		'setting_cls_wap_set' => 'WAP浏览设置',
		'setting_wapcharset' => 'WAP 字符集：<br />UTF-8 编码占用字节较小，但兼容性较差，遇到乱码等情况可能导致页面无法浏览。<br />UNICODE 编码占用字节较大，但兼容性比UTF-8编码好很多，推荐使用。',
		'setting_waplimit' => 'WAP 页面长度控制：<br />为了提高兼容性请设置为大于0的整数，建议设置为：300-2000 之间。',
		'setting_showforums' => 'WAP推荐版块：<br />为方便WAP用户查看站点帖子，请设置您想要推荐给WAP用户的版块。',
	),
	'urlcheck'	=> array(
		'urlcheck_info'=>'每行一个站点地址，被加入白名单的站点将在开启外链提醒功能后也不提示（外链提醒功能请在发帖设置中开启）<br>填写站点的格式如：phpwind.net,同时所有此站点的二级域名也被加入白名单中',
		'urlcheck_list'=>'以下为被加入白名单的站点地址:',
	),
	'help'	=> array(
		'help_basic'=>'站点帮助管理',
		'help_add'=>'添加帮助项目',
		'help_info'=>'帮助操作注意事项：<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. 标题不能为空<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. 内容支持html<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. 无限级项目，随意创建、删除。删除会将下级项目下所有帮助删除，请小心操作。',
		'help_submit' => '确认删除',
		'help_help'=>'帮助项目',
		'help_case'=>'上级项目',
		'help_topcase'=>'作为顶级',
		'help_order'=>'显示顺序',
		'help_addchild'=>'添加子项目',
		'help_content'=>'内容<br />(支持html代码)',
		'help_warn'=>'url链接<br />[指定到一个地址，方便发布各种形式的帮助]<br />
	注:填写此处，内容无须填写',
	),
	'sethtm'	=> array(
		'sethtm_info'=>'功能说明:<br>此功能把站点的URL转换成更容易被搜索引擎收录的形式，普通用户只需开启静态目录部署功能即可，URL形式如：http://www.phpwind.net/thread.php?fid-2.html，不过这种形式中包含有(.php?), 可能会被某些搜索引擎判定为是动态页面, 而降低网站内容被收录的机率，为了能更好的提高您的网站被搜索引擎收录的机率，可以使用参照下面的方法对服务器进行相关设置',
		'sethtm_title'=>'静态目录部署',
		'sethtm_htmifopen'=>'是否开启静态目录部署功能',
		'sethtm_dir'=>'静态目录',
		'sethtm_ext'=>'静态目录扩展名设置',
		'sethtm_way'=>'使用方法：',
		'sethtm_wayinfo'=>'以apache服务器为例介绍使用方法.<br/><br/> 1.在静态目录部署中，开启静态目录部署功能，将静态目录设置为"-htm-"，将静态目录扩展名设置为:".html"<br/> &nbsp; &nbsp;默认的URL形式为 "http://www.phpwind.net/thread.php?fid=2"<br/> &nbsp; &nbsp;新的URL形式为&nbsp; &nbsp; "http://www.phpwind.net/thread-htm-fid-2.html"<br/> &nbsp; &nbsp;这种纯静态形式的URL更易被搜索引擎收录<br/><br/>2.Apache Web Server 的配置<br/> &nbsp; &nbsp;首先确定加载了 Mod_rewrite 模块，方法: 检查 conf/httpd.conf 中是否存在以下两段代码 (具体路径可能会有所不同，但形式基本是一样的):<br/><br/>(一)LoadModule rewrite_module     libexec/mod_rewrite.so<br/> (二)AddModule mod_rewrite.c<br/><br/> 如果存在，那么在配置文件（通常就是conf/httpd.conf）中加入如下代码。此时须注意，如果网站使用通过虚拟主机来定义，请务必加到虚拟主机配置中去，否则可能无法使用。改好后然后将 Apache 重启. <br/><br/>&lt;IfModule mod_rewrite.c&gt;<br/> RewriteEngine On<br/> RewriteRule ^(.*)-htm-(.*)$ $1.php?$2<br/>&lt;/IfModule&gt;<br/><br/>',
	),
	'setforum'	=> array(
		'setforum_setforum'=>'快捷操作',
		'setforum_add_info' => '说明：可以添加新分类，新版块>',
		'setforum_addcate' => '添加新分类&nbsp;新分类名称',
		'setforum_addforum' => '添加新版块&nbsp;新版块名称',
		'setforum_selfup'=>'选择父版块',
		'setforum_ifsave'=>'继承父版块设置',
		'setforum_title' => '编辑版块',
		'setforum_open' => '全部展开',
		'setforum_close' => '全部关闭',
		'setforum_forumname' => '[顺序]版块名称',
		'setforum_forumadmin' => '版主',
		'setforum_editforum' => '双击修改名称',
		'setforum_addforum' => '添加版块',
		'action=edit'	=> array(
			'name' => '版块基本权限',
			'setforum_name' => '版块名称：[支持 html 代码]',
			'setforum_across'=>'版块横排设置 (填写每排显示版块个数，不使用请留空或填 "0")',
			'setforum_dirname'=>'版块二级目录设置(填写版块所属二级目录)',
			'setforum_forum_fup' => '选择上级版块',
			'setforum_bbs' => '站点版块',
			'setforum_keywords' => '设置版块关键字，有利于搜索引擎(50字节以内)',
			'setforum_descrip' => '版块简介，[支持 html 代码](250字节以内)<br />同时也有利于搜索引擎',
			'setforum_showsub'=>"首页是否显示子版块",
			'setforum_logo' => '版块图标 注：此处设置只有在“核心设置”->“首页细节”->“版块图片logo”处选择为自定义才有效',
			'setforum_f_type' => '新类别<br> 开放:默认版块.正规:游客无法进入.<br>隐藏:无权限的将不可见.',
			'setforum_forum' => '开放版块',
			'setforum_former' => '正规版块',
			'setforum_hidden' => '隐藏版块',
			'setforum_allowtype' => '允许发表的主题类型',
			'setforum_allowtype_1' => '普通',
			'setforum_allowtype_2' => '投票',
			'setforum_allowtype_4' => '活动',
			'setforum_allowtype_8' => '悬赏',
			'setforum_allowtype_16' => '商品',
			'setforum_allowtype_32' => '辩论',
			'setforum_recycle' => '允许版主回收站管理',
			'setforum_recycle_4' => '还原',
			'setforum_recycle_8' => '清空',
			'setforum_ifhide2' => '是否在文章系统中显示<br>将出现在文章系统首页左下方，主题列表和文章页面右下方的社区推荐中',
			'setforum_link'=>'版块链接 (填写此项，当进入版块时将转向您填写的链接地址)',
			'setforum_lock'=>'锁定多少天以前发表的主题不允许回复 (留空或设为 "0" 不限制)',
			'setforum_cutnums'=>'主题列表标题显示字节数 (一个汉字占两个字节，留空或设为 "0" 不限制)',
			'setforum_threadnum'=>'主题列表每页显示主题个数 注：留空使用“核心-主题列表细节”中设定的值',
			'setforum_readnum'=>'浏览帖子每页显示文章个数 注：留空使用“核心-帖子阅读细节”中设定的值',
			'setforum_newtime'=>'显示新帖图片标识时间设置 (单位：分钟) 注：留空使用“核心-主题列表细节”中设定的值',
			'setforum_orderway'=>'版块默认主题排序关键字<br>影响效率，建议使用按‘最后发表’排序',
			'setforum_asc'=>'版块默认主题排序方式',
			'setforum_rewarddb'=>'悬赏帖设置',
			'setforum_rw_day'=>'(单位：天)',
			'setforum_reward_best'=>'最佳答案：',
			'setforum_smallest'=>'(最小积分)',
			'setforum_reward_active'=>'热心助人：',
			'setforum_reward_credit'=>'悬赏积分：',
			'setforum_uploadset'=>'上传附件与下载附件积分控制管理',
			'setforum_u_type_set'=>'附件积分类型设置：',
			'setforum_u_upload'=>'上传附件奖励积分：',
			'setforum_u_upload_1'=>'小于0表示扣除积分',
			'setforum_u_download'=>'下载附件扣除积分：',
			'setforum_u_download_1'=>'小于0表示奖励积分',
			'setforum_u_img'=>'浏览图片扣除积分：',
			'setforum_viewsub' => '是否只显示子版块(选 "是" 将不显示父版块的帖子)',
			'setforum_hide' => '是否允许隐藏帖 注：此设置同时受用户组权限限制，开启用户组权限中的发表隐藏帖功能方有效',
			'setforum_sell' => '是否允许出售帖 注：此设置同时受用户组权限限制，开启用户组权限中的发表出售帖功能方有效',
			'setforum_encode' => '是否允许加密帖',
			'setforum_anonymous'=>'是否允许匿名帖',
			'setforum_recommend'=>'是否开启帖子推荐功能',
			'setforum_inspect'=>'是否开启“版主标记已阅”功能',
			'setforum_watermark'=>'是否允许使用图片水印功能(在图片水印开启条件下)',
			'setforum_copy'=>'是否允许使用帖子水印功能:防止帖子内容被复制',
			'setforum_check' => '发帖审核设置(管理员不受此限制)<br>开启发帖审核功能后,用户发表的主题或回复需要通过审核后才能在前台显示',
			'setforum_check_0'=>'无',
			'setforum_check_1'=>'审核主题',
			'setforum_check_2'=>'审核回复',
			'setforum_check_3'=>'审核主题和回复',
			'setforum_admin_dig'=>'版主推荐',
			'setforum_admin_commend'=>'是否开启版主推荐功能',
			'setforum_autocommend'=>'是否启用推荐列表自动生成功能<br />当推荐列表不足设置的最大显示条数时，将按所选排序方式自动生成',
			'setforum_autocommend_0'=>'不生成',
			'setforum_autocommend_1'=>'按发帖时间',
			'setforum_autocommend_2'=>'按最后回复时间',
			'setforum_autocommend_3'=>'按点击率',
			'setforum_autocommend_4'=>'按回复数',
			'setforum_autocommend_5'=>'按精华帖',
			'setforum_commendlist'=>'推荐列帖子列表',
			'setforum_commendnum'=>'推荐列表最大显示条数',
			'setforum_commendlength'=>'标题最大字节数',
			'setforum_commendtime'=>'推荐列表数据缓存间隔(秒)<br />当开启推荐列表自动生成功能时，定期更新推荐列表(建议值 3600，0为不更新)',
			'setforum_tpc_type' => '版块主题分类',
			'setforum_if_addtype' => '是否在标题前面加上主题分类名称',
			'setforum_allow_sel' => '普通会员主题分类管理',
			'setforum_forcetype'=> '强制分类',
			'setforum_allowtype'=> '允许分类',
			'setforum_closetype'=> '关闭分类',
			'setforum_addtype' => '[添加主题类型]',
			'setforum_addnewtype' => '新增加主题类别名称',
			'setforum_creditlimit' => '版块访问积分限制',
			'setforum_postnumneed' => '至少需要发帖数',
			'setforum_forumsell' => '版块访问权限出售设置',
			'setforum_forumsell_credit' => '版块访问权限出售积分',
			'setforum_sellprice' => '版块访问权限出售价格',
			'setforum_stime' => '期限(单位：天)',
			'setforum_cprice' => '积分价格',
			'setforum_rmbprice' => 'RMB价格',
			'setforum_adds' => '[添加]',
			'setforum_forumtime' => '版块发帖时间域限制',
			'setforum_allowtime' => '允许发帖的时间域<br />(全不选则不限制)',
			'setforum_unit'=>'点',
			'setforum_forumright' => '版块权限--全不选则默认为开放版块',
			'setforum_forumpwd' => '版块密码',
			'setforum_intro' => '不加密请清空!如果版块已加密,显示的密码为32位MD5密码,不必再修改!',
			'setforum_visit' => '允许浏览版块',
			'setforum_read'  => '允许浏览帖子',
			'setforum_post' => '允许发表主题',
			'setforum_reply' => '允许发表回复',
			'setforum_upload' => '允许上传附件',
			'setforum_down' => '允许下载附件',
			'setforum_otherforumset' => '版块设置横向操作<br />功能说明：<br>利用此功能可将一个或多个设置同时应用到其它版块中，不再需要逐个版块设置，使操作更加简便<br />操作说明：<br>1. 选中需要进行横向操作的权限设置前面的复选框<br>2. 在右边的复选框中选择需要进行横向操作的版块<br>3. 然后提交即可完成版块权限横向操作<br />注：<br>1. 选择版块时可使用 ‘Ctrl’ 键进行多选，也可使用 ‘Shift’ 键或拖动鼠标连续选择多个版块<br>2. 不使用此功能，请不要选中权限设置前面的复选框和右边的复选框中版块',
		),
		'action=credit'	=> array(
			'name'=>'版块积分设置',
			'setforum_warn'=>'注：威望积分设置支持1位小数点，其他积分只允许整数，留空则使用“核心-积分设置”处的默认值 ！',
		),
	),
	'uniteforum'	=> array(
		'uniteforum_title' => '合并版块',
		'uniteforum_info' => '1.源版块将被删除，源版块的所有帖子将移动目标版块中<br>2.有子版块的版块不能合并到其他版块<br>3.分类不能使用合并功能',
		'uniteforum_from' => '源版块',
		'uniteforum_to' => '目标版块',
	),
	'creathtm'	=> array(
		'creathtm_info' => '功能说明:<br>1 . 采用静态 html 方式来缓存主题内容从而大幅度节约数据库资源,并使浏览速度有质的飞跃.适合于大型网站<br>2 . 占用较多服务器空间,一般占用与您RDBMS同等空间<br>3 . 加密帖(出售,加密,隐藏)不会生成htm页面<br>4 . 如果您的空间打开 safe_mode 如果您对此不了解,建议不要使用此功能<br>5 . 使用此功能后用户的真实信息将滞后,请不定期重新生成所有 html 文件!<br>6 . 使用此功能后请不要采用多种风格.更不能使用图片.附件防盗链功能!<br>7 . 使用此功能后将自动启用点击率延迟更新功能<br><br/>模版管理说明：<br>1.可选择一次性生成所有版块的静态模版，也可以选择生成单个版块的静态模版<br>2.当您取消某版块的静态模版功能时请删除相应的 html 数据,以节约空间!',
		'creathtm_title' => '静态模版功能',
		'creathtm_forum' => '选择需要使用静态模版<br>功能的版块',
		'creathtm_forum_admin' => '静态模版管理',
		'creathtm_sel_forum' => '选择创建模版的版块',
		'creathtm_type' => '操作类型',
		'creathtm_creat' => '创建',
		'creathtm_forumnum' => '各版块最大主题生成个数<br />(留空则全部生成)',
		'creathtm_pernum' => '每批生成主题数',
	),
	'forumsell'	=> array(

	),
	'singleright'	=> array(
		'singleright_list'=>'用户访问权限',
		'singleright_fastoperate'=>'快捷操作',
		'singleright_soname'=>'搜索用户名：',
		'singleright_addname'=>'添加用户名：',
		'singleright_so'=>'搜　索',
		'singleright_add'=>'添　加',
		'singleright_user_list'=>'版块用户访问权限列表',
		'action=user'	=> array(
			'name'=>'搜索用户管理权限',
			'singleright_user_info'=>'可以给单个用户指定版块管理权限，而不需要修改该用户原来所属的用户组头衔!<br />添加用户必须是属于系统组或特殊组的用户。<br />',
			'singleright_gid'=>'用户组：',
			'singleright_fid'=>'版　块：',
			'singleright_addright'=>'添加用户管理权限',
			'singleright_pwuser'=>'用　户　名　：',
			'singleright_group'=>'系统组或特殊组用户',
			'singleright_forum'=>'权限作用版块：',
			'singleright_admin_list'=>'版块用户管理权限列表',
		),
		'action=group'	=> array(
			'name'	=>'用户组管理权限',
			'singleright_group_info'=>'可以给单用户组指定版块管理权限，而不需要修改该用户组里的全局管理权限!',
			'singleright_add_so'=>'添加或搜索：',
			'singleright_groupcache'=>'选择用户组',
			'singleright_forumcache'=>'选择版块',
			'singleright_admins_list'=>'版块用户组管理权限列表',
		),
	),
	'article'	=> array(
		'superdel_atc_info' => '1.删除符合条件的帖子用于清理站点冗余数据,此操作不可恢复,请谨慎使用！<br>2.用户组成员根据用户组权限设置取得相应批量删除权限<br>3.版主拥有所管辖的版块（分类）发布的批量删除的权限<br>功能说明:<br/>使用删除主题功能可删除某个会员发表的所有主题(包括回复)<br>使用删除回复功能可删除某个会员发表的所有回复',
		'superdel_member_info' => '删除符合条件的用户,用于清理站点冗余数据,此操作不可恢复,请谨慎使用！',
		'superdel_deltpc' => '删除主题',
		'superdel_digest' => '保留精华置顶',
		'superdel_database'=>'分表数据库',
		'superdel_post_by' => '主题发表于<br>(可只用单个条件，下同)',
		'superdel_lastreply' => '主题最后被回复于',
		'superdel_tid_scope'=>'指定 tid 范围<br>(可只用单个条件)',
		'superdel_pid_scope'=>'指定 pid 范围<br>(可只用单个条件)',
		'superdel_hit_by' => '浏览人数小于',
		'superdel_tpc_of' => '的主题',
		'superdel_reply_by' => '回复人数小于',
		'superdel_tpc_author' => '按作者删除(主题作者)<br>(多个作者用","分隔)',
		'superdel_match' => '可使用通配符 "*"',
		'superdel_keyword' => '关键字包含(多个关键字用","分隔)',
		'superdel_userip' => '根据用户IP查找',
		'superdel_show_num' => '每页显示行数',
		'superdel_direct' => '直接删除(直接删除符合条件的项目)',
		'superdel_delrpl' => '删除回复',
		'superdel_tid' => '所属主题ID<br>(多个主题ID用","分隔)',
		'superdel_delrpl_info' => '此功能可删除单个或多个主题的所有回复',
		'superdel_author_by' => '按作者删除(回复作者)<br>(多个作者用","分隔)',
		'superdel_content_less' => '内容少于',
		'superdel_content_more' => '内容大于',
		'superdel_pernum' => '每批处理的个数',
		'superdel_atc_list' => '文章列表',
		'superdel_deluser' => '删除用户',
		'superdel_group' => '用户组',
		'superdel_name' => '用户名包含',
		'superdel_post_more' => '发帖数小于(帖)',
		'superdel_oltime' => '在线时间小于(小时)',
		'superdel_reg_early' => '注册时间大于',
		'superdel_member' => '所有会员',
		'superdel_howlong' => '多久未登录',
		'superdel_order' => '排序方式',
		'superdel_userlist' => '用户列表',
		'superdel_system' => '系统头衔',
	),
	'message'	=> array(
		'superdel_msg_info' => '删除符合条件的短消息,用于清理站点冗余数据,此操作不可恢复,请谨慎使用！<br>系统信息删除2.0之前请用"系统信息"用户名搜索，2.0开始请用"SYSTEM"用户名搜索',
		'superdel_delmsg' => '删除短消息',
		'superdel_msgtype' => '信箱类型',
		'superdel_delall' => '全部删除',
		'superdel_rebox' => '收件箱',
		'superdel_sebox' => '发件箱',
		'superdel_public' => '群发消息',
		'superdel_newmsg' => '是否保留新消息',
		'superdel_msg' => '天前的短消息',
		'superdel_msglist' => '短消息列表',
		'superdel_item' => '删除项目',
		'superdel_item_member' => '用户信息',
		'superdel_item_thread' => '用户主题',
		'superdel_item_post' => '用户回复',
		'superdel_item_message' => '用户短消息',
		'superdel_bit' => '字节',
		'superdel_msg'=>'删除个数',
		'superdel_msglog'=>'删除个人通信记录',
		'superdel_msgdate'=>'天前的通信记录',
		'superdel_lines'=>'每次删除个数',
		'superdel_send' => '发件人',
		'superdel_accept' => '收件人',
	),
	'recycle'	=> array(
		'type=topic'	=> array(
			'name'=>'主题回收站',
			'recycle_info'=>'1.还原：可将被删除的帖子主题或回复还原到原来的版块帖子中。2.删除：将帖子主题或回复从回收站中彻底删除,不可恢复3.清空：删除所有回收站帖子4.删除记录：删除回收站的记录,但并没有彻底删除帖子内容,不可恢复',
	'recycle_title'=>'回收站',
		),
		'type=reply'	=> array(
			'name'=>'回复回收站',
			'recycle_info'=>'1.还原：可将被删除的帖子主题或回复还原到原来的版块帖子中。2.删除：将帖子主题或回复从回收站中彻底删除,不可恢复3.清空：删除所有回收站帖子4.删除记录：删除回收站的记录,但并没有彻底删除帖子内容,不可恢复',
	'recycle_title'=>'回收站',
		),
	),
	'draftset'	=> array(
		'draftset_list'=>'草稿箱列表',
		'draftset_list_del'=>'批量删除草稿',
		'draftset_guide'=>'草稿箱管理',
		'draftset_content'=>'草稿内容',
		'draftset_guide2'=>'批量删除',
		'draftset_username'=>'用户名：',
		'draftset_keyword'=>'关键字：',
		'draftset_delnums'=>'删除个数限制：',
		'draftset_clear'=>'清空草稿箱(删除草稿箱所有信息)',
	),
	'tpccheck'	=> array(
		'tpccheck_info' => '版块开启 "主题审核" 功能时，只有经过管理员审核的主题才会在前台显示',
		'tpccheck_list' => '帖子验证',
		'tpccheck_forums'=>'所属分类',
		'tpccheck_sel_forum'=>'选择分类',
	),
	'postcheck'	=> array(
		'postcheck_info'=> '版块开启 "回复审核" 功能时，只有经过管理员审核的回复才会在主题中显示',
		'postcheck_list'=>'回复验证',
		'postcheck_forums'=>'所属分类',
		'postcheck_select_forum'=>'选择分类',
		'postcheck_database'=>'分表数据库',
		'postcheck_topic'=>'所在主题',
	),
	'report'	=> array(
		'report_title'=>'会员报告帖处理',
		'report_tpc'=>'帖子位置',
		'report_username'=>'反映用户',
		'report_enter'=>'进入帖子',
	),
	'tagset'	=> array(
		'tagset_manager' => '标签管理',
		'tagset_add' => '添加标签',
		'tagset_set' => '标签设置',
		'tagset_iftag' => '是否开启标签功能',
		'tagset_tagindex' => '首页显示热门标签个数 (0为不显示)',
		'tagset_keyword' => '标签名：',
		'tagset_ifhot' => '热门标签：',
		'tagset_ls' => '标签长度：',
		'tagset_ns' => '使用数：',
		'tagset_deltag' => '删除标签',
		'tagset_allowhot' => '允许为热门标签',
		'tagset_unallowhot' => '不允许为热门标签',
		'tagset_adds' => '批量添加',
		'tagset_add_tag' => '添加 TAG ,多个用“,”分开',
		'tagset_list' => '标签列表',
		'tagset_usetag' => '使用的标签',
		'tagset_linktag' => '关联的标签',
	),
	'pwcode'	=> array(
		'pwcode_code'=>'自定义代码',
		'pwcode_addcode'=>'添加自定义代码',
		'pwcode_editcode'=>'编辑自定义代码',
		'pwcode_intro'=>'自定义代码功能说明',
		'pwcode_tag'=>'标签：<br />方括号中的标签代码，如 [tag] 的标签为 tag',
		'pwcode_title'=>'标题：',
		'pwcode_icon'=>'图标文件名：',
		'pwcode_param'=>'搜索模式：<br />内容搜索规则',
		'pwcode_pattern'=>'参数类型：',
		'pwcode_pat_0'=>' 允许任意字符 ',
		'pwcode_pat_1'=>' 允许字符和数字 ',
		'pwcode_pat_2'=>' 只允许数字',
		'pwcode_replace'=>'替换规则：',
		'pwcode_descrip'=>'提示语言：<br />各个参数的提示语言<br />每行一个,分别代表 {1} , {2} , {3} 的语言提示',
	),
	'setform'	=> array(
		'setform_info'=>'预设帖子格式说明功能：您可以设定帖子格式，以便于发此类帖子时可以省时省力，比如发出租信息等。(支持html代码)',
		'setform_list'=>'格式列表',
		'setform_add' =>'添加帖子格式',
		'setform_edit' =>'编辑帖子格式',
		'setform_title' =>'预设帖子格式',
		'setform_title2' =>'帖子格式',
		'setform_subject' =>'帖子格式标题',
		'setform_tagmenu' =>'栏目编辑器',
		'setform_name' =>'栏目名称：',
		'setform_type' =>'栏目类型：',
		'setform_type_0' =>'文本输入框',
		'setform_type_1' =>'下拉选择框',
		'setform_content' =>'选项内容：<br />(一行一个)',
		'setform_addcol_2' =>'修 改',
		'setform_addcol_0' =>'删 除',
		'setform_alert_1' =>'标题不能为空',
		'setform_alert_2' =>'您没有添加相关栏目',
	),
	'topiccate' => array(
	),
	'postcate' => array(
	),
	'setbwd'	=> array(
		'setbwd_repword' => '替换词语',
		'setbwd_banword' => '禁用词语',
		'setbwd_alarm'   => '报警词语',
		'setbwd_new' => '新增词语',
		'setbwd_batch' => '导入导出',
		'setbwd_renew' => '更新系数',
		'setbwd_repinfo' => '替换词语：<br />　　在浏览帖子时，会将帖子中的需要替换的词语替换为对应内容<br />',
		'setbwd_bwdinfo' => '禁用词语：<br />　　在发表文章时，检查文章内容中是否含有禁用词语，如果含有禁用词语将被禁止发表，已经发表的文章中如果含有禁用词语将被替换为对应的内容<br />',
		'setbwd_alarminfo' => '报警词语：<br />　　在发表文章时，检查文章内容中是否含有报警词语，如果含有报警词语将自动将文章设为需要管理员审核才能查看(报警词语无需设置替换词)<br />',
		'setbwd_upinfo' => '更新系数：<br />　　更新系数是用来控制帖子内容是否需要替换的一个参数。如果您希望当前词语过滤设置对以前发的帖子也生效，请选中自动更新选项(或者更改更新系数)。更新操作将在此操作后第一次浏览帖子时进行，每个帖子只更新一次。否则当前词语过滤设置只对新发表的帖子有效。<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;注：添加、修改不良词语需要选中更新选项；删除、修改替换词语时无须更新<br />',
		'setbwd_insertinfo' => '批量导入：<br />　　选择需要导入的文件(txt)，点击提交<br />　　内容规则：<br />　　1、a=>b (将词语a替换成词语b)<br />　　2、a|b|c=>d (将词语a、b、c替换成词语d)<br />　　3、一行一条记录，替换词语不设置时将使用默认词语',
		'setbwd_word' => '不良词语',
		'setbwd_replace' => '替换为',
		'setbwd_update' => '更新系数',
		'setbwd_update_1' => '自动更新',
		'setbwd_update_0' => '不更新',
		'setbwd_type' => '词语类型： ',
		'setbwd_insert' => '批量导入',
		'setbwd_insert_file' => '导入文件',
		'setbwd_mrep' => '默认词语',
		'setbwd_out' => '词语导出',
		'setbwd_out_file' => '导出文件名<br />文件路径 /data',
		'setbwd_out_file2' => ' .txt (只允许字符数字和下划线)',
		'setbwd_update_re' => '更新系数调整',
		'setbwd_now' => '当前系数',
		'setbwd_desvalue' => '期望系数：',
		'setbwd_submit' => '更 新',
	),
	'postcache'	=> array(
		'postcache_guide'=>'表情组使用帮助',
		'postcache_info'=>'添加表情组：请先在你的图片文件夹下的post/smile/文件夹下建立相应的文件夹
	添加表情：一个表情组下所有的表情图片都要上传至该表情组的文件夹下才可以进行添加
	表情名称：当鼠标悬停时将出现该表情的介绍
	表情描述：如果设置表情描述，使用该表情时将出现相应的语言描述',
		'postcache_postmanage'=>'表情管理',
		'postcache_montion_name' => '表情组名称',
		'postcache_pic_path' => '图片路径',
		'postcache_montion_vieworder' => '显示顺序',
		'postcache_shownum' => '默认显示个数',
		'postcache_smile_manage' => '分类表情管理',
		'postcache_smile_delete' => '删除此表情分类',
		'postcache_add_montion' => '添加表情组',
		'postcache_delsmiles' => '删除表情分类也会删除该分类下的所有表情\\\n将会导致前台的所有该分类下的表情图片无法再显示，您确认要删除吗？',
		'postcache_delsmile' => '删除表情请注意：\\\n\\\n删除该表情将会导致前台的该表情图片无法再显示，您确认要删除吗？',
		'postcache_oldsmile' => '已经成功添加的表情',
		'postcache_img' => '图片名称',
		'postcache_pic_view' => '图片预览',
		'postcache_img_descrip'=>'图片描述',
		'postcache_newsmile' => '该目录下尚未被添加的表情',
	),
	'level'	=> array(
		'level_editgroup' => '用户组编辑',
		'level_batch' => '导入导出',
		'level_help' => '详细帮助',
		'level_intro' => '会员组：级别按照会员发的帖子数自动进行级别判断并更新。<br>
	系统组：属于站点管理层，系统组成员由站点管理员设定<br />
	特殊组：可以设置管理权限的组别，区别于系统组，特殊组可以进行出售<br />
	默认组：默认组别不可删除，当其他组别未设置权限时，则使用该默认权限<br />
	注：批量添加的用户组权限设置为默认，需要单独进行权限编辑。',
		'level_close' => '收起',
		'level_open' => '展开',
		'level_edit_mem' => '会员组编辑',
		'level_group' => '头衔',
		'level_group_pic' => '等级图片号',
		'level_credit' => '升级点数需求',
		'level_getimg' => '选择等级图片',
		'level_edit_right' => '权限',
		'level_addmem' => '添加会员组：',
		'level_addsys' => '添加系统组：',
		'level_addspl' => '添加特殊组：',
		'level_default' => '默认用户组',
		'level_pic_sel' => '等级图片选择',
		'action=help'	=> array(
			'name'	=> '用户组帮助',
			'level_info' => '站点的用户组分为会员组、系统组、特殊组、默认组。<br />&nbsp;&nbsp;会员组：级别按照会员发的帖子数自动进行级别判断并更新。<br>
&nbsp;&nbsp;系统组：属于站点管理层，系统组成员由站点管理员设定<br />
&nbsp;&nbsp;特殊组：可以设置管理权限的组别，区别于系统组，特殊组可以进行出售<br />
&nbsp;&nbsp;默认组：默认组别不可删除，当其他组别未设置权限时，则使用该默认权限',
			'level_pic_intro' => '等级图片号说明',
		),
		'action=editgroup'	=> array(
			'name'	=> '用户组权限',
			'basic_allowhide' => '可隐身登录',
			'basic_allowread' => '可浏览帖子',
			'basic_allowsearch' => '搜索控制',
			'basic_allowmember' => '可查看会员列表',
			'basic_allowprofile' => '可查看会员资料',
			'basic_atclog' => '是否允许查看帖子操作记录',
			'basic_show' => '是否允许使用展区功能',
			'basic_allowreport' => '可使用报告功能',
			'basic_upload' => '有头像上传功能',
			'basic_allowportait' => '能使用头像链接',
			'basic_allowhonor' => '能使用个性签名功能',
			'basic_allowmessege' => '能发送短消息',
			'basic_allowsort' => '能查看统计排行',
			'basic_alloworder' => '能使用主题排序(主题列表页面)',
			'basic_viewipfrom' => '能查看ip来源',
			'basic_searchtime' => '两次搜索时间间隔(秒)',
			'basic_schtime' => '搜索发表时间范围',
			'basic_signnum' => '个人签名最大字节数',
			'basic_imgwidth' => '签名中的图片最大宽度',
			'basic_imgheight' => '签名中的图片最大高度',
			'basic_fontsize' => '签名中[size]标签的最大值',
			'basic_maxmsg' => '最大短消息数目',
			'basic_maxsendmsg' => '每日最大发送短消息数目',
			'basic_msggroup' => '可使用“只接收特定用户组的短消息”的功能',
			'basic_ifmemo' => '能使用便笺的功能',
			'basic_pergroup' => '哪些用户组权限可以查看',
			'basic_maxfavor' => '收藏夹容量',
			'basic_maxgraft' => '草稿箱容量',
			'basic_pwdlimitime' => '强制用户组密码变更',
			'basic_maxcstyles' => '自定义风格数量',
			'read_allowpost' => '可发表主题',
			'read_allowrp' => '可回复主题',
			'read_allownewvote' => '可发起投票',
			'read_modifyvote' => '投票发起人能修改投票选项',
			'read_allowvote' => '可参与投票',
			'read_viewvote' => '能查看投票用户',
			'read_allowactive' => '可发活动帖',
			'read_allowreward' => '可发悬赏帖',
			'read_allowgoods' => '可发商品帖',
			'read_allowdebate' => '可发辩论帖',
			'read_htmlcode' => '可发html帖',
			'read_media' => '发布多媒体是否允许自动播放',
			'read_allowhidden' => '可发隐藏帖',
			'read_allowsell' => '可发出售帖注：此设置同时受版块权限限制，开启版块权限中的发表出售帖功能方有效',
			'read_allowencode' => '可发加密帖注：此设置同时受版块权限限制，开启版块权限中的发表加密帖功能方有效',
			'read_anonymous' => '可发匿名帖',
			'read_dig' => '是否允许推荐帖子',
			'read_leaveword' => '楼主有留言权限',
			'read_allowdelatc' => '可删除自己的帖子',
			'read_atccheck' => '开启版块文章审核时,发表的文章是否需要管理员审核',
			'read_markable' => '站点评分权限',
			'read_markset' => '评分设置 说明：复选框不选中或者评分上限、评分限制任何一项留空和设为0，前台将无法使用该评分类型',
			'read_postlimit' => '每天最多允许发表多少篇帖子',
			'read_postpertime' => '灌水预防',
			'read_edittime' => '编辑时间约束(分钟)',
			'att_allowupload' => '上传附件权限',
			'att_allowdownload' => '下载附件权限',
			'att_allownum' => '一天最多上传附件个数',
			'att_uploadtype' => '上传附件允许后缀和最大尺寸',
			'special_allowbuy' => '允许购买',
			'special_selltype' => '特殊组购买使用币种',
			'special_sellprice' => '每日价格(积分)',
			'special_rmbprice' => '每日价格(现金)',
			'special_selllimit' => '用户至少需要购买特殊组的天数限制',
			'special_sellinfo' => '特殊组描述',
			'system_allowadmincp' => '可进后台',
			'system_superright' => '超级管理权限',
			'systemforum_viewhide' => '查看加密帖(隐藏，加密，出售，匿名)',
			'systemforum_postpers' => '灌水 说明：不受灌水时间限制',
			'systemforum_replylock' => '回复锁定帖',
			'systemforum_viewip' => '查看IP 说明：浏览帖子时显示',
			'systemforum_topped' => '置顶权限',
			'systemforum_typeadmin' => '前台" 精、锁、提、亮、压 "管理权限',
			'systemforum_tpctype' => '进行主题分类管理',
			'systemforum_tpccheck' => '进行主题验证管理',
			'systemforum_delatc' => '批量删除主题',
			'systemforum_moveatc' => '批量移动帖子',
			'systemforum_copyatc' => '批量复制帖子',
			'systemforum_modother' => '删除单一帖子（包括回复）',
			'systemforum_deltpcs' => '编辑用户帖子',
			'systemforum_viewcheck' => '可以查看需要验证的帖子',
			'systemforum_viewclose' => '可以查看关闭帖子',
			'systemforum_delattach' => '可以删除附件',
			'systemforum_shield' => '屏蔽单一主题',
			'systemforum_unite' => '合并主题',
			'systemforum_remind' => '帖子管理提醒功能',
			'systemforum_pingcp' => '管理评分记录',
			'systemforum_inspect' => '拥有“版主标记已阅”权限',
			'systemforum_allowtime' => '不受版块“发帖时间域权限”限制',
			'systemforum_banuser' => '禁言用户的权限',
			'systemforum_bantype' => '永久禁言用户',
			'systemforum_banmax' => '禁言时间限制',
		),
	),
	'userstats'	=> array(
		'userstats_title' => '用户组成员统计',
		'userstats_view' => '查看用户组会员',
	),
	'upgrade'	=> array(
		'upgrade_title' => '会员组提升方案',
		'upgrade_rate' => '比率',
		'upgrade_post' => '发帖数',
		'upgrade_info' => 'PHPWind 提供了一套灵活的等级提升方案，可以根据综合积分来划分用户等级，设定一个好的等级提升方案能更好的体现站点等级系统的价值<br />综合积分：综合积分是按照会员组提升方案中设定的积分比率来计算的<br>计算方法：各项积分*比率的和为综合积分的值<br />如等级提升方案设置<br>发帖数 : 1<br>威望 &nbsp; &nbsp;: 0.5<br>金钱 &nbsp; &nbsp;: -1<br>其他 &nbsp; &nbsp;: 0<br />综合积分计算方法如下：<br>发贴数*1 + 威望*0.5 + 金钱*(-1)',
	),
	'editgroup'	=> array(
		'editgroup_info' => '1.可以批量添加用户组成员<br />2.先选择要编辑的用户组名称，再在文本框中输入要加入该用户组的会员名，然后提交 ( 多个会员名之间用","分隔)<br />3.用此功能批量禁言用户,禁言类型为永久禁言,要使用定期禁言请到会员禁言功能设置',
		'editgroup_title' => '添加用户组成员',
		'editgroup_members' => '用户组成员',
	),
	'uptime'	=> array(
		'editgroup_info' => '1.可以批量添加用户组成员<br />2.先选择要编辑的用户组名称，再在文本框中输入要加入该用户组的会员名，然后提交 ( 多个会员名之间用","分隔)<br />3.用此功能批量禁言用户,禁言类型为永久禁言,要使用定期禁言请到会员禁言功能设置',
		'editgroup_title' => '添加用户组成员',
		'editgroup_members' => '用户组成员',
	),
	'setuser'	=> array(
		'setuser_edit_info' => '主要功能：用户组管理，未验证会员审核，禁言组设置，会员编辑，（版主请到版块管理处设置）<br>1.用户组管理：<br>搜索会员并可设置会员为管理员.总版主.和其他特殊组.<br>在"用户组"处选择要进行操作的用户组，按搜索进入该用户组的管理，要去除该用户组的某个会员只需将他的系统头衔设为普通会员或其他用户组头衔<br>2.未验证会员审核：<br>当开启新注册会员需要管理员验证功能时可以对需要验证的新会员进行管理，在"用户组"处选择"验证会员"选项，按搜索进入验证会员的管理，要通过某个会员验证只需将此会员的系统头衔设为普通会员或其他用户组头衔<br>3.单个会员管理：<br>在"用户名包含"处填写会员ID（可以使用通配符进行模糊查找），按搜索进入对会员资料编辑<br>注:只有超管才能编辑管理员的资料',
		'setuser_edit_title' => '编辑用户',
		'setuser_all' => '不限制',
		'setuser_name_contain' => '用户名包含<br>(可使用通配符 "*")',
		'setuser_name_s' => '精确匹配',
		'setuser_email' => '邮箱<br>(可使用通配符 "*")',
		'setuser_lastip' => '最后登录IP<br>(可使用通配符 "*")',
		'setuser_reg_early' => '注册时间大于',
		'setuser_howlong' => '多久未登录',
		'setuser_order' => '排序',
		'setuser_pernum' => '每页显示行数',
		'setuser_groups_info' => '用户组头衔管理<br>此功能可查看用户的附加用户组头衔',
		'setuser_groups_title' => '用户组头衔管理',
		'setuser_bygroups'=>'附加用户组头衔',
		'setuser_add_title' => '添加用户',
		'setuser_add_info' => '使用此功能可以在开启禁止注册新用户功能时,由管理员添加特定用户   <br>超管(站点创始人)可以使用此功能添加站点管理员(普通管理员无此权限)',
		'setuser_password' => '密&#160;&#160;码',
		'setuser_update_post' => '更新会员发帖数',
		'setuser_update_post_info' => '提示:将根据数据库中的帖子记录来重新统计用户的发帖数<br>不建议使用，除非您希望校正所有用户的发帖数为数据库中实际存在的帖子数',
		'setuser_update_num' => '每批更新个数',
		'setuser_editgroup' => '1.此功能可以批量修改会员头衔 <br>2.此功能设置为禁言组的用户将被永久禁言',
		'setuser_list' => '用户列表',
		'setuser_system' => '系统头衔',
		'setuser_groups'=>'附加用户组头衔',
		'setuser_edit_name' => '用户名(如无特殊需要请不要修改)',
		'setuser_edit_pwd' => '新密码(如不更改请留空)',
		'setuser_confirm' => '确认密码(修改密码时需要输入)',
	),
	'unituser'	=> array(
		'unituser_title'=>'合并会员',
		'unituser_info'=>'将 原用户 的积分 , 帖子数据合并到 目标用户 中，同时删除 原用户 的记录',
		'unituser_username'=>'原用户数字ID（多个用户用‘,’分隔）',
		'unituser_newname'=>'目标用户数字ID',
	),
	'banuser'	=> array(
		'banuser_info' => '1.自动禁言：自动禁言在管理员给会员评分时起作用',
		'banuser_title' => '自动禁言设置',
		'banuser_ifuse' => '是否使用此功能',
		'banuser_by' => '积分依据',
		'banuser_term' => '定期禁言',
		'banuser_forever' => '永久禁言(不需要设定禁言期限)',
		'banuser_limit' => '禁言期限(天)',
		'banuser_credit' => '积分小于',
		'banuser_banuser' => '会员禁言',
		'banuser_force'=>'强制禁言',
		'banuser_free' => '解除禁言',
	),
	'viewban'	=> array(
		'viewban_info' => '封禁用户列表，管理员可使用此功能解除封禁用户',
		'viewban_type2' => '禁言类型',
		'viewban_term' => '定期禁言',
		'viewban_forever' => '永久禁言',
		'viewban_force'=>'强制禁言',
		'viewban_time2' => '禁言时间',
		'viewban_list' => '禁言用户',
		'viewban_range' => '禁言范围',
		'viewban_type' => '封禁类型',
		'viewban_time' => '封禁时间',
		'viewban_limit' => '封禁天数',
		'viewban_reason' => '禁言原因',
		'viewban_freeban' => '解禁?',
		'viewban_global' => '全局禁言',
	),
	'delmember'	=> array(
		'superdel_atc_info' => '1.删除符合条件的帖子用于清理站点冗余数据,此操作不可恢复,请谨慎使用！<br>2.用户组成员根据用户组权限设置取得相应批量删除权限<br>3.版主拥有所管辖的版块（分类）发布的批量删除的权限<br>功能说明:<br/>使用删除主题功能可删除某个会员发表的所有主题(包括回复)<br>使用删除回复功能可删除某个会员发表的所有回复',
		'superdel_member_info' => '删除符合条件的用户,用于清理站点冗余数据,此操作不可恢复,请谨慎使用！',
		'superdel_msg_info' => '删除符合条件的短消息,用于清理站点冗余数据,此操作不可恢复,请谨慎使用！<br>系统信息删除2.0之前请用"系统信息"用户名搜索，2.0开始请用"SYSTEM"用户名搜索',
		'superdel_deltpc' => '删除主题',
		'superdel_digest' => '保留精华置顶',
		'superdel_database'=>'分表数据库',
		'superdel_post_by' => '主题发表于<br>(可只用单个条件，下同)',
		'superdel_lastreply' => '主题最后被回复于',
		'superdel_tid_scope'=>'指定 tid 范围<br>(可只用单个条件)',
		'superdel_pid_scope'=>'指定 pid 范围<br>(可只用单个条件)',
		'superdel_hit_by' => '浏览人数小于',
		'superdel_tpc_of' => '的主题',
		'superdel_reply_by' => '回复人数小于',
		'superdel_tpc_author' => '按作者删除(主题作者)<br>(多个作者用","分隔)',
		'superdel_match' => '可使用通配符 "*"',
		'superdel_keyword' => '关键字包含(多个关键字用","分隔)',
		'superdel_userip' => '根据用户IP查找',
		'superdel_show_num' => '每页显示行数',
		'superdel_direct' => '直接删除(直接删除符合条件的项目)',
		'superdel_delrpl' => '删除回复',
		'superdel_tid' => '所属主题ID<br>(多个主题ID用","分隔)',
		'superdel_delrpl_info' => '此功能可删除单个或多个主题的所有回复',
		'superdel_author_by' => '按作者删除(回复作者)<br>(多个作者用","分隔)',
		'superdel_content_less' => '内容少于',
		'superdel_content_more' => '内容大于',
		'superdel_pernum' => '每批处理的个数',
		'superdel_atc_list' => '文章列表',
		'superdel_deluser' => '删除用户',
	),
	'checkreg'	=> array(
		'usercheck_email' => '需要email验证的用户如果无法通过email激活帐号，管理员可使用此功能激活用户帐号',
		'usercheck_list' => '需要验证的用户',
		'usercheck_newrg' => '此功能可将未验证会员组的用户编入普通会员组',
	),
	'checkemail'	=> array(
		'usercheck_email' => '需要email验证的用户如果无法通过email激活帐号，管理员可使用此功能激活用户帐号',
		'usercheck_list' => '需要验证的用户',
		'usercheck_newrg' => '此功能可将未验证会员组的用户编入普通会员组',
	),
	'customcredit'	=> array(
		'customcredit_info' => '<br>可以查看和管理用户自定义积分',
		'customcredit_title' => '自定义积分管理',
		'customcredit_name' => '自定义积分名称',
		'customcredit_value' => '自定义积分值',
	),
	'customfield'	=> array(
                'customfield_info'=>'此功能允许管理员自定义用户信息，用户在注册和编辑个人资料时填写这些栏目信息<br>允许编辑：&nbsp;&nbsp;&nbsp;当设置不允许用户编辑时，用户在第一次填写信息后，将不能自行修改自定义用户信息<br>必填内容：&nbsp;&nbsp;&nbsp;当设置为必填项目时，用户注册或编辑个人资料时，必须填写栏目信息后才能提交成功<br>用户组权限：当设置用户组权限后，只有指定用户组有权限查看自定义用户信息<br>帖子中显示：可以设置在帖子页面左侧用户信息处显示自定义用户信息',
                'customfield_title'=>'用户栏目管理',
		'action=add'	=> array(
			'name' => '添加用户栏目',
			'customfield_edit' => '编辑用户栏目',
			'customfield_title2'=>'栏目标题',
			'customfield_type'=>'栏目类型',
			'customfield_editable'=>'允许编辑',
			'customfield_required'=>'必填',
			'customfield_titleadd'=>'栏目标题<br>请控制在50字节以内',
			'customfield_descrip'=>'栏目描述<br>请控制在255字节以内',
			'customfield_maxlen'=>'长度控制<br>用户输入长度限制(最大：255字节)',
			'customfield_requiredadd'=>'必填内容<br>是否要求用户在注册和编辑个人资料时必须填写此项',
			'customfield_viewinread'=>'在帖子中显示<br>在帖子页面左侧用户信息处显示',
			'customfield_viewinread2'=>'帖子中显示',
			'customfield_editableadd'=>'允许编辑<br>用户第一次填写信息后，是否允许再次自行修改',
			'customfield_viewright'=>'查看权限<br>允许查看用户此栏目信息的用户组，不选将对所有用户组开放查看权限',
			'customfield_options'=>'选项内容<br>当栏目类型为单选框时需要设置选项内容，每行为一个选项<br>格式：索引=内容，建议使用数字做索引<br>例如：<br>1=诺基亚<br>2=摩托罗拉<br>3=三星',
			'customfield_typeadd'=>'栏目类型<br>一旦选定，请不要随意修改，否则将可能造成栏目信息显示错误',
			'customfield_apply'=>'是否启用该栏目<br>栏目填加后您可以选择暂时关闭该栏目使用',
		),
	),
	'ipban'	=> array(
		'ipban_info' => '每行一个ip，被禁止了一个IP将无法访问站点<br>可以禁止单个IP地址格式如：192.0.0.1<br>也可以禁止一段ip格式如：192.0.0',
		'ipban_list' => '以下为被禁止的IP:',
	),
	'ipstates'	=> array(
		'ipstates_info'=>'可以统计每月到访的ip量，每日到访的ip量，站长可以根据统计清楚的了解站点的流量情况。',
		'ipstates_title'=>'IP统计设置',
		'ipstates_intro'=>'是否开启IP统计',
	),
	'ipsearch'	=> array(
		'ipsearch_info'=>'IP搜索工具:<br>1.可以根据用户名搜索该用户使用过的所有IP.<br>2.可以根据IP地址搜索使用过该IP的所有用户(此项功能存在负载性,大型站点请谨慎使用!).<br>',
		'ipsearch_byname'=>'根据用户名搜索',
		'ipsearch_byip'=>'根据IP地址搜索',
		'ipsearch_intro'=>'由于该功能具有一定的负载性，会员超过10万，帖子超过30万的站点系统将自动禁止使用该功能',
		'ipsearch_allname'=>'搜索该IP相关记录',
		'ipsearch_date'=>'使用时间',
		'ipsearch_option'=>'选项',
		'ipsearch_allip'=>'查看该用户使用过IP',
		'ipsearch_user'=>'查看用户资料',
		'ipsearch_tpc'=>'查看该用户的主题',
		'ipsearch_rpl'=>'查看该用户的回复',
	),
	'adminlog'	=> array(
		'record_code'=>'自定义代码',
		'record_info' => '1.　为了保证后台的安全性,系统只允许站点创始人和管理员删除操作日记<br>2.　系统必须保留前100条后台管理日志.',
		'record_nums' => '每页条数',
		'record_title' => '管理日志',
		'record_view' => '查看全部日志',
		'record_del' => '删除多余管理日志',
		'record_pwd' => '错误密码',
		'record_log' => '操作日志',
		'record_time' => '操作时间',
		'record_other'=>'其他',
		'record_point' => '点数',
		'record_position' => '查看文章位置',
		'record_reason' => '评分理由',
	),
	'forumlog'	=> array(
		'forumlog_info' => '1.　为了保证后台的安全性,系统只允许站点创始人和管理员删除操作日记<br>2.　系统保留三天的站点管理日志，只允许删除三天前的日志.',
		'forumlog_log' => '操作日志',
		'forumlog_object' => '对象',
		'forumlog_del' => '删除多余管理日志',
	),
	'creditlog'	=> array(
		'creditlog_log' => '积分日志',
		'creditlog_backup' => '日志备份',
		'creditlog_info' => '1、积分日志：该功能详细记录某种积分的流通情况，帮助站长更加清晰地掌握站点的积分状况！<br />2、积分统计：可以统计某个时间段内任何积分的流通总额',
		'creditlog_table' => '日志表',
		'creditlog_flow_log' => '积分流通日志',
		'action=sort'	=> array(
			'creditlog_sort' => '积分统计',
		),
		'action=backup'	=> array(
			'name' => '日志表状态',
			'creditlog_table2' => '表名',
			'creditlog_nums' => '记录数',
			'creditlog_size' => '数据表大小',
			'creditlog_time' => '记录时间',
			'creditlog_descrip1' => '
					1、如果您的积分日志不是非常重要，建议您核对积分后，清空此表<br />
					2、如果您希望继续保留此日志，建议您启用新日志表，并将该表保存为备份日志<br />
					当前状态：',
			'creditlog_descrip2' => '数据庞大，建议按照以上方法执行',
			'creditlog_descrip3' => '正常，无需任何操作',
			'creditlog_clear' => '清空日志表',
			'creditlog_bak' => '备份日志表',
			'creditlog_default' => '默认',
			'creditlog_main_table' => '主表',
			'creditlog_bak_table' => '备份表',
			'creditlog_none_log' => '没有备份日志表!',
		),
	),
	'adminrecord'	=> array(
		'adminrecord_info' => '1.　为了保证后台的安全性,系统只允许站点创始人和管理员删除管理记录<br>2.　系统必须保留前100条后台管理记录.',
		'adminrecord_title' => '管理记录',
		'adminrecord_time' => '操作时间',
		'adminrecord_reason' => '操作理由',
		'adminrecord_del' => '删除多余管理记录',
		'adminrecord_confirm' => '是否要删除多余管理记录？',
	),
	'bakout'	=> array(
		'bakup_out_info' => '您可以根据自己的需要选择需要备份的数据库表,导出的数据文件可用"数据恢复"功能。<br>为了数据安全,备份文件采用时间戳命名保存,如果备份数据超过设定的大小程序会自动采用分卷备份功能，请耐心等待直到程序提示全部备份完成。<br>附件的备份只需手工转移附件目录和文件即可,风格备份也同! PhpWind不提供单独备份。',
	),
	'bakin'	=> array(
		'bakup_in_info' => '本功能在恢复备份数据的同时,将覆盖原有数据,请确定是否需要恢复,以免造成数据损失。<br>数据恢复功能只能恢复由当前版本导出的数据文件,其他软件导出格式可能无法识别。<br>如果一个备份文件有多个分卷，您只需任选一个备份文件导入，程序会自动导入其他分卷',
	),
	'repair'	=> array(
		'repair_info' => '修复表 : 此操作可修复数据库在进行查询，删除，更新等操作时产生的错误<br>优化表 : 此操作可优化数据库表结构，以获得更好的数据库运行效率',
		'repair_title' => '数据库优化',
		'repair_table' => '数据库表',
		'repair_sel' => '选择',
		'repair_repair' => '修复表',
		'repair_optimize'=>'优化表',
		'repair_other'=>'非PHPWind数据库表 (站点插件或其他系统的数据库表)',
		'repair_title2' => '数据库优化信息',
		'repair_msg' => '信息',
	),
	'ptable'	=> array(
		'ptable_list'=> '分卷管理',
		'ptable_info'=>'数据库分卷技术实现将一个数据量非常大的表拆分成多个数据较小的表，从而提高数据库查询效率，让您的站点在超大数据量下仍然能高效运行',
		'ptable_intro'=> '功能说明',
		'ptable_topic_step'=> '主题内容表分卷功能使用步骤',
		'ptable_topic_info'=> '1. 使用“创建新主题表”功能创建一张新的主题表 <br />2. 设置tid分界点，当tid大于某个表的分界点并且小于下个表的分界点时，新增主题数据将插入到这个表<br />3. 分卷功能设置完成！<br />注意：<br>1. 使用分卷功能前请务必先关闭站点<br>2. 当tid范围出现蓝色字体并有“转移”字样时，表明该表的数据与其他表存在重叠区间，应该使用转移功能修复，否则将导致部分主题内容无法显示。',
		'ptable_addtopic'=> '创建新主题表',
		'ptable_topic_msg'=> '已有主题内容表信息（pw_tmsgs）',
		'ptable_table'=> '表名',
		'ptable_nums' => '记录数',
		'ptable_size' => '数据表大小',
		'ptable_tid' => 'tid范围',
		'ptable_creatime' => '创建时间',
		'ptable_tidbound' => 'tid分界点',
		'ptable_move' => '转移',
		'ptable_post_step'=> '回复表分卷功能使用步骤',
		'ptable_post_info'=> '1. 使用“创建新回复表”功能创建一张新的回复表（系统默认将新创建的表设为“当前回复表”，新增回复数据将记录在“当前回复表”表里） <br />2. 回复表分卷功能设置完成！<br />注意：<br />1. 使用分卷功能前请务必先关闭站点 <br />2. 如果您原来的‘回复数据表(pw_posts)’已经非常大，您可以使用‘数据转移’功能，将部分数据转移到新的回复表，来降低原来的回复表的负载',
		'ptable_addpost'=> '创建新回复表',
		'ptable_movedata'=> '数据转移',
		'ptable_post_msg'=> '已有回复表信息（pw_posts）',
		'ptable_posts'=> '当前回复表',
		'ptable_m_posts'=> '更改当前回复表',
		'ptable_movepost'=> '转移回复',
		'ptable_intro_more'=> '将“源回复数据表”里指定“tid范围”的回复数据转移到“目标回复数据表”，从而达到降低系统负载的目的，根据服务器负载情况调整“每次转移帖子数”',
		'ptable_tfrom'=> '源回复数据表',
		'ptable_tto'=> '目标回复数据表',
		'ptable_lines'=> '每次转移帖子数',
		'ptable_dataname'=> '数据表',
		'ptable_topic_move'=> '转移主题',
		'ptable_datatid'=> '数据表 tid 范围',
		'ptable_data_tid'=> '需转移的数据 tid 范围',
	),
	'updatecache'	=> array(
		'update_title' => '缓存管理',
		'update_cache' => '更新站点缓存',
		'update_cache_info' => '数据转换后或前台不能正常访问时，可以使用此功能更新所有缓存',
		'update_member' => '更新会员总数',
		'update_member_info' => '可修复会员总数统计错误问题',
		'update_article' => '更新版块帖子数记录',
		'update_article_info' => '更新所有版块的主题数和文章数统计<br/>数据转换后或前台文章数统计不正常时，可使用此功能修复',
		'update_num' => '每批更新个数',
		'update_online'=>'初始化在线列表',
		'update_online_info'=>'前台在线用户列表发生错乱时，可使用此功能修复',
		'update_topped'=>'更新置顶帖统计',
		'update_topped_info' => '置顶帖显示不正常，可使用此功能修复',
		'update_topic' => '更新主题回复数记录',
		'update_topic_info' => '更新主题的回复数统计<br>当浏览帖子页面回复显示不正常时，可以使用此功能修复 (不建议使用)',
		'update_group' => '更新系统组成员头衔',
		'update_group_info' => '使用此功能可修复版主头衔错误和系统组头衔错误的问题',
		'update_level' => '更新会员组头衔',
		'update_level_info' => '根据积分方案更新会员组头衔<br>每次更改升级点数需求或会员组提升方式后需要使用此功能更新会员组头衔',
		'update_post' => '更新会员发帖数',
		'update_post_info' => '提示:将根据数据库中的帖子记录来重新统计用户的发帖数<br>不建议使用，除非您希望校正所有用户的发帖数为数据库中实际存在的帖子数',
		'update_digest'=>'更新会员精华数',
		'update_digest_info'=>'修复所有会员的精华帖个数统计',
		'update_ipfrom'=>'更新文章中的IP来源',
	),
	'pwcache'	=> array(
		'pwcache_info'=> '1、PW缓存库主要用于各种站点模式的不同应用<br />
		2、请根据各个元素的使用情况而选择需要开启的缓存',
		'pwcache_title'=>'PW缓存库设置',
		'pwcache_intro'=>'开启PW缓存库<br />(未开启则直接进行数据库查询,需要开启时，请务必点击后面的更新缓存按钮)',
		'pwcache_ifpwcache_1'=>' 会员信息(总发帖,本月发帖,今日发帖,在线时间,会员积分)',
		'pwcache_ifpwcache_2'=>' 热门帖(总回复数)<br />',
		'pwcache_ifpwcache_4'=>' 热门帖(每天回复数)<br />',
		'pwcache_ifpwcache_8'=>' 热门帖(每周回复数)<br />',
		'pwcache_ifpwcache_16'=>' 人气帖(总点击数)<br />',
		'pwcache_ifpwcache_32'=>' 人气帖(每天点击数)<br />',
		'pwcache_ifpwcache_64'=>' 人气帖(每周点击数)<br />',
		'pwcache_ifpwcache_128'=>' 最新帖<br />',
		'pwcache_ifpwcache_256'=>' 最新回复<br />',
		'pwcache_ifpwcache_512'=>' 最新图片<br />',
	),
	'guestdir'	=> array(
		'guestdir_guide' => '删除游客缓存文件',
		'guestdir_guide2' => '清空主题列表缓存文件',
		'guestdir_info' => '游客缓存文件统计共有；占用空间',
		'guestdir_info2' => '主题列表缓存文件统计共有 占用空间',
		'guestdir_range' => '选择范围',
		'guestdir_topic' => '主题列表页',
		'guestdir_nums' => '每批处理的个数',
		'guestdir_clear' => '清空',
	),
	'chmod'	=> array(
		'chmod_guide'=>'说明：<br>1.777属性通过：文件属性正常。<br>2.需要设置777属性：没有设置777属性，需要管理员使用FTP工具手动设置777属性，否则程序可能无法正常运行。<br>3.文件不存在：文件不存在，请检查文件是否上传完整。<br>',
		'chmod_title'=>'文件属性检查',
		'chmod_right'=>'777属性通过',
		'chmod_fail'=>'需要设置777属性',
		'chmod_nofile'=>'文件不存在',
	),
	'safecheck'	=> array(
		'safecheck_check'=>'文件搜索检查',
		'safecheck_file'=>'程序文件检查',
		'safecheck_cache'=>'缓存目录检查',
		'safecheck_info'=>'文件安全检查功能说明：<br />　1、文件搜索检查：输入自定义关键字(可疑代码)，搜索程序文件，查找出所有出现关键字的文件<br />　2、程序文件检查：与官方提供的程序进行对比，提醒您站点上的文件是否被篡改<br />　3、缓存目录检查：查找所有缓存文件，确认文件的安全性<br />　4、保障站点安全有效地运行',
	),
	'datastate'	=> array(
		'datastate_topic'=>'主题统计',
		'datastate_reply'=>'回复统计',
		'datastate_regmen'=>'注册统计',
		'datastate_postmen'=>'发帖人数统计',
	),
	'viewtody'	=> array(

	),
	'hackcenter'	=> array(
		'hackcenter_guide' => '插件安装步骤',
		'hackcenter_info' => '1. 将插件文件上传到插件目录(hack/)<br />2. 在“未安装插件”列表中选择安装您需要的插件',
		'hackcenter_title1' => '已安装插件',
		'hackcenter_title2' => '未安装插件',
		'hackcenter_name' => '插件名称',
		'hackcenter_admin' => '插件管理',
		'hackcenter_sign' => '插件目录',
		'hackcenter_ifopen' => '前台显示方式',
		'hackcenter_del' => '卸载',
		'hackcenter_click' => '点击管理此插件',
		'hackcenter_0'=>'不显示',
		'hackcenter_1'=>'下拉菜单显示',
		'hackcenter_2'=>'直接显示',
		'hackcenter_confirm' => '卸载插件将同时删除插件相关的数据，您确定要卸载此插件吗?',
		'hackcenter_op' => '管理选项',
		'hackcenter_install' => '安装',
	),
	'setstyles'	=> array(
		'setstyles_list'=>'风格列表',
		'setstyles_add'=>'添加风格',
		'setstyles_edit'=>'编辑风格',
		'setstyles_core' => '风格核心文件编辑',
		'setstyles_guide'=>'css设置',
		'setstyles_showcss'=>'css显示方式设置',
		'setstyles_showcss_0'=>'直接 html 显示',
		'setstyles_showcss_1'=>'以 link 方式外部引用样式',
		'setstyles_filename'=>'风格文件名',
		'setstyles_define'=>'自定义风格名',
		'setstyles_default'=>'默认',
		'setstyles_core' => '风格核心文件编辑',
		'setstyles_file' => '编辑的风格名称',
		'setstyles_path' => '此风格在image目录下的文件夹名称:<br ／>(请不要任意修改,如果需要请先手动修改image下的目录名)',
		'setstyles_tplpath' => '此风格在template目录下的风格文件夹名称:',
		'setstyles_allset' => '整体风格设置',
		'setstyles_yeyestyle' => '表格内部样式:',
		'setstyles_yeyestyle_1' => '竖线风格',
		'setstyles_yeyestyle_0' => '横线风格',
		'setstyles_width' => '表格宽度：(例: 98% 或 920px)',
		'setstyles_mwidth' => '头部和尾部表格宽度：(例: 98% 或 920px)',
		'setstyles_bgcolor' => '全局背景颜色：',
		'setstyles_linkcolor' => '全局链接颜色：',
		'setstyles_tablecolor' => '表格外边框颜色：',
		'setstyles_tdcolor' => '表格内边框颜色：',
		'setstyles_tableset' => '表格样式颜色设置',
		'setstyles_headcolor' => '表格标题栏颜色：',
		'setstyles_headborder' => '表格标题栏下边框颜色：',
		'setstyles_headfontone' => '标题栏主要字体链接颜色：',
		'setstyles_headfonttwo' => '标题栏次要字体链接颜色：',
		'setstyles_cbgcolor' => '表格副标题栏颜色：',
		'setstyles_cbgborder' => '表格副标题栏下边框颜色：',
		'setstyles_cbgfont' => '表格副标题栏字体颜色：',
		'setstyles_forumcolorone' => '站点列表颜色一：',
		'setstyles_forumcolortwo' => '站点列表颜色二：',
		'setstyles_extcss' => '自定义css样式：',
	),
	'userpay'	=> array(
		'userpay_info'=>'
使用网上支付相关说明：<br>
1. 开启网上支付功能即被视为接受“PHPWind”相关协议，如有任何疑义，请关闭此功能<br>
2. 支付过程出现问题请及时和PHPWind 官方取得联系<br>
3. 因使用网站自身安全原因引起的非法支付PHPWind 不负任何责任',
		'userpay_set'=>'网上支付设置',
		'userpay_ifopen'=>'是否开启网上支付功能',
		'userpay_whyclose'=>'网上支付功能关闭原因',
		'userpay_tenpayinfo'=>'财付通信息',
		'userpay_tenpay'=>'商户号',
		'userpay_tenpay_ap'=>'点击这里申请 财付通 商户帐号',
		'userpay_tenpaycode'=>'商户密钥',
		'userpay_alipayinfo'=>'支付宝信息',
		'userpay_alipay'=>'支付宝帐号',
		'userpay_alipay_partnerID'=>'合作者身份（partnerID）',
		'userpay_alipay_getpartnerID'=>'签约地址 (您可以通过 PHPWind 提供的签约入口来免费获得一个支付宝的合作者身份ID，拥有该ID，您可以在支付宝网站上查询到该ID产生的所有交易历史。如果您没有签约或者签约合同尚未生效，请留空这里，将使用 PHPWind 提供的统一ID进行交易)',
		'userpay_alipay_alipaykey' => '您可以登入您的支付宝账号页面，进入“商家服务”查看您的“交易安全校验码”',
		'userpay_alipay_key'=>'交易安全校验码（key）',
		'userpay_alipay_ap'=>'请点击这里注册 支付宝 帐号',
		'userpay_paypalinfo'=>'贝宝信息',
		'userpay_paypal'=>'贝宝帐号',
		'userpay_paypalcode'=>'贝宝公共密钥',
		'userpay_paypal_ap'=>'注册 贝宝 帐号',
		'userpay_99billinfo'=>'快钱信息',
		'userpay_99bill'=>'商户编号',
		'userpay_99billcode'=>'快钱密钥',
		'userpay_99bill_ap'=>'注册 快钱 帐号',
		'userpay_step'=>'具体步骤',
		'userpay_step_1'=>'（一）开通支付宝支付步骤：<br>
	1. 如果您已经拥有一个支付宝帐号，在下面“支付宝帐号”栏填写您的支付宝帐号即可开通支付宝支付功能<br />
	2. 如果您还没有支付宝帐号，请先注册一个支付宝帐号，


	请点击这里注册 支付宝帐号

	<br>注：除官方站点另行通知以外，PHPWind 提供的支付宝支付服务每笔交易收取 1.5% 的手续费。',
		'userpay_step_2'=>'（二）开通财付通支付步骤：<br />
	1. 申请财付通商户帐号，点
	击这里申请财付通商户帐号
	2. 申请成功后将商户号和商户密钥填入下面对应的文本框',
		'userpay_step_3'=>'（三）开通贝宝支付步骤：<br>
	1. 注册一个贝宝帐号，

	注册 贝宝帐号<br>

	2. 将贝宝帐号填写到下面对应的文本框<br>
	3. 开启贝宝“即时付款通知”<br>
	 &nbsp; &nbsp; 登录贝宝网站：进入 我的贝宝 &raquo; 用户信息 &raquo; 即时付款通知习惯设定 &raquo; 编辑 开启“即时付款通知”并填写“通知URL”<br>
	 &nbsp; &nbsp; 通知URL是 您的站点网址 + \'/paypal.php?verifycode=\' + 贝宝公共密钥<br>
	 &nbsp; &nbsp; 格式如：http://www.phpwind.net/paypal.php?verifycode=贝宝公共密钥',
		'userpay_step_4'=>'（四）开通快钱支付步骤：<br />
	1. 注册一个快钱帐号，
	注册快钱帐号
	<br />
	3. 将“快钱商户号”和“快钱密钥”填入下面相应的文本框中',
	),
	'orderlist'	=> array(
		'orderlist_admincp'=>'订单管理',
		'orderlist_all'=>'所有订单',
		'orderlist_success'=>'已完成订单',
		'orderlist_fail'=>'未完成订单',
		'orderlist_type'=>'订单类型',
		'orderlist_num'=>'订单号',
		'orderlist_payemail'=>'付款帐号',
		'orderlist_money'=>'支付金额',
		'orderlist_state'=>'交易状态',
		'orderlist_time'=>'交易时间',
		'orderlist_end'=>'完成支付',
		'orderlist_detail'=>'详情',
		'orderlist_end_intro'=>'完成支付说明',
		'orderlist_1'=>'未完成',
		'orderlist_2'=>'已支付，等待用户确认',
		'orderlist_3'=>'已完成',
		'orderlist_nopay'=>'未支付订单',
		'orderlist_finish'=>'完成充值',
		'orderlist_intro1'=>'由于支付宝系统在传输支付状态的过程可能会出现一些不可预料的问题，导致用户实际已经支付成功，但交易币没有充值成功~',
		'orderlist_intro2'=>'请核对订单信息后将付款帐号填入下方对应的文本框内，再使用“完成充值”功能完成本次订单的充值',
		'orderlist_order1'=>'积分充值',
		'orderlist_order2'=>'道具购买',
		'orderlist_order3'=>'版块权限购买',
		'orderlist_order4'=>'特殊组购买',
		'orderlist_order5'=>'注册码购买',
	),
	'announcement'	=> array(
		'notice_list'=>'公告管理',
		'notice_add'=>'公告添加',
		'notice_title1'=>'更新公告信息',
		'notice_info'=>'公告管理：可查看特定 公告范围（全局公告与版块公告）下的所有公告，针对某条公告进行 编辑 删除 操作，设置所有公告的 显示顺序。<br />
	公告添加：可根据需求，在指定的 公告范围 添加公告信息，公告不允许添加多媒体。<br />
	公告状态：每个公告均有是否启用的开关。当在关闭状态下，状态为 已关闭。当在开启状态下，若 当前时间小于开始时间，状态为 未发布；若 当前时间大于结束时间，状态为 已过期；若 当前时间在开始时间与结束时间之间，状态为 已发布。公告仅当在 已发布 状态，前台才显示。',
		'notice_selrange'=>'公告范围：',
	),
	'sendmail'	=> array(
		'sendmail_info'=>'	存在未完成的邮件群发任务',
		'sendmail_title'=>'邮件群发',
		'sendmail_title2'=>'邮件群发确认',
		'sendmail_by_0'=>'按用户组',
		'sendmail_by_1'=>'在线用户',
		'sendmail_by_2'=>'按注册时间',
		'sendmail_toname' =>'接收用户',
		'sendmail_member' =>'普通会员',
		'sendmail_time' =>'格式：yyyy-mm-dd，会员注册时间范围',
		'sendmail_percount' =>'每批发送个数',
		'sendmail_content' =>'表示用户的邮件地址',
		'sendmail_count' =>'接收用户总数',
		'sendmail_ren' =>'人',
		'sendmail_num' =>'每批发送',
		'sendmail_fen' =>'封',
		'sendmail_sent' =>'已完成发送',
		'sendmail_lasttime' =>'最后发送时间',
		'sendmail_reuser' =>'邮件接收用户',
		'sendmail_online' =>'当前在线的会员',
		'sendmail_setime' =>'注册时间在',
		'sendmail_subject' =>'邮件标题',
		'sendmail_contents' =>'邮件内容',
		'sendmail_start' =>'开始发送',
	),
	'sendmsg'	=> array(
		'sendmsg_title'=>'短消息群发',
		'sendmsg_online'=>'在线用户',
		'sendmsg_toname' =>'接收用户',
	),
	'present'	=> array(
		'present_title'=> '节日送礼',
		'present_bygroup'=>'按用户组',
		'present_online'=>'在线用户',
		'present_toname' => '接收用户',
		'present_member' => '普通会员',
		'present_give_credit' => '赠送积分',
		'present_nums' => '每批发送个数',
	),
	'setads'	=> array(
		'setads_info' => '功能说明:<br>就是鼓励会员宣传网站的功能。只要用户把您站点的 url 推荐给其他朋友，并引导其他人访问您的网站。',
		'setads_infoadd'=>"注意：需要注册是指：会员引导的朋友需要注册之后， 会员才会增加贡献值；而勿需注册则不限制，只要引导其他人访问该网站，就会增加!",
		'setads_title' => '功能设置',
		'setads_intro' => '是否允许用户使用宣传代码!',
		'setads_ads_2'=>"需要注册",
		'setads_ads_1'=>"勿需注册",
	),
	'share'	=> array(
		'sharelink_list' => '友情链接管理',
		'sharelink_add' => '添加友情链接',
		'sharelink_edit' => '编辑友情链接',
		'sharelink_guide' => ' 友情链接添加说明：<br> 1、特殊链接(显示顺序<0，每行显示一个)<br> 2、普通连接(显示顺序>=0)',
		'sharelink_name' => '站点名称',
		'sharelink_logo' => '站点LOGO<br>[设置文字链接请留空]',
		'sharelink_admin' => '站点主人',
	),
	'sitemap'	=> array(
		'sitemap_info' => '网站地图功能(Sitemaps)使您能够告知搜索引擎您网站中可供抓取的网址，以便搜索引擎可以更智能地收录您的网站信息，适用于各种大小的网站。',
		'sitemap_title' => '网站地图设置',
		'sitemap_updateperi' => '更新周期(小时)(建议值：12小时)',
		'sitemap_num' => '生成列表数目(建议值：1000)',
		'sitemap_create' => '重新生成网站地图',
	),
	'rebang'	=> array(
		'rebang_info'=>'1、热榜排行可结合PW缓存库进行使用<br />2、如果开启了热榜排行之后，首页的浏览速度减慢，请开启PW缓存库里面相对应的缓存！<br />3、如果开启了PW缓存库，热榜排行中的缓存内容是从PW缓存库中取得，PW缓存库中的内容未更新时，不能确保热榜排行处的缓存能更新到最新',
		'rebang_title'=>'首页热榜设置',
		'rebang_ifopen'=>'是否开启首页热榜',
		'rebang_position'=>'显示位置',
		'rebang_cateform'=>'栏目管理',
		'rebang_name'=>'栏目标题名称',
		'rebang_type'=>'栏目内容类型',
	),
	'plantodo'	=> array(
		'plantodo_info'=>'
1、计划任务是一项使系统在规定时间自动执行某些特定任务的功能。

2、合理设置执行时间，能有效地为服务器减轻负担。

3、对于如“期限头衔自动回收”此类需每天更新的计划任务建议不设置月和周的更新时间，否则对于购买一或几天的头衔的用户可能在一周或者一月内都无法回收头衔。',
		'plantodo_m_task'=>'计划任务管理',
	),
	'addplan'	=> array(
		'addplan_plantask_info'=>'
1、计划任务是一项使系统在规定时间自动执行某些特定任务的功能。
2、计划任务与系统核心紧密关联，上传不当的文件可能造成站点无法正常运行。
3、关于计划任务的添加，您需要上传相应执行文件到 ./require/plan/目录下，如果需要进行详细设置的，还需要上传相应的设置文件和模版文件
(模版文件上传到 ./template/admin/ 目录下，文件名为 *_set.htm；设置文件上传到 ./require/plan/ 目录下，文件名为 *_set.php)。',
		'addplan_task_title'=>"任务标题",
		'addplan_task_month'=>"每月几号执行",
		'addplan_task_week'=>"每周星期几执行",
		'addplan_task_day'=>"每日几点执行",
		'addplan_task_hour'=>"每小时几分钟执行",
		'addplan_task_ifopen'=>"是否开启该计划任务",
	),
	'modeset'	=> array(
		'modeset_info1'=>'1、可以根据自己站点的定位来选择合适自己的站点模式<br />
2、二级域名：请设置全称,如:mode.phpwind.net',
		'modeset_sel_mod'=>'模式选择',
		'modeset_name'=>'模式名称',
		'modeset_intro'=>"模式说明",
		'modeset_sel'=>"选择默认",
		'modeset_cache'=>"更新",
		'modeset_cache1'=>"更新缓存",
		'modeset_default'=>"站点模式",
		'modeset_bbs'=>"传统的社区",
		'modeset_admin'=>'管理',
		'modeset_uninstall'=>'未安装模式',
		'modeset_dir'=>'模式目录',
		'modeset_install' => '安装',
		'modeset_mode_ifopen' => '是否开启',
		'modeset_mode_default'=>'选择默认',
		'modeset_set_uninstall'=>'卸载',
		'modeset_setpage'=>'配置',
		'modeset_setpage1'=>'配置页面',
		'modeset_domain'=>"二级域名",
	),
	/*
	'modestamp'	=> array(
		'modestamp_info'=>'1、可以自己添加分类和模块<br />
2、系统默认的模块和分类无法编辑和删除',
		'modestamp_catelist'=>'分类列表',
		'modestamp_onlysign'=>'唯一标识',
		'modestamp_default'=>'默认模块',
		'modestamp_insidecate'=>'内置分类',
		'modestamp_view'=>"查看模块",
		'modestamp_addcate'=>"添加新分类",
		'modestamp_modlist'=>"模块列表",
		'modestamp_fuc'=>"调用函数",
		'modestamp_insidemod'=>'内置模块',
		'modestamp_setdef'=>'设为默认',
		'modestamp_c_setdef'=>'点击设为默认',
		'modestamp_addmod'=>'添加新模块',
		'modestamp_type'=>'type属性:',
		'modestamp_fid'=>'fid属性:',
		'modestamp_special'=>'special属性:',
		'modestamp_cachetime'=>'缓存时间(秒):',
		'modestamp_special'=>'special属性:',
		'modestamp_ifextra'=>'是否为外部函数:',
		'modestamp_modifycate'=>'修改分类',
		'modestamp_editblock'=>'分类 -- 模块修改',
	),
	'modepush'	=> array(
		'modepush_guide1'=>'推送位置列表',
		'modepush_guide2'=>'推送文章列表',
		'modepush_guide3'=>'推送帖子编辑',
		'modepush_manager'=>'管理',
		'modepush_subject'=>"文章标题",
		'modepush_time'=>"时间范围",
		'modepush_pushtime'=>"推送时间",
		'modepush_repush'=>"重新推送",
		'modepush_condense'=>"摘要：",
	),
*/
	'rightset'	=> array(
		'rightset_info'=>'1、可添加或删除后台管理权限。<br />
2、根据需求设置每个用户组的后台管理权限。',
		'rightset_title'=>'用户组后台权限管理',
		'rightset_title2'=>'添加后台权限',
		'rightset_title3'=>'后台权限分配',
	),
	'manager'	=> array(
		'manager_info'=>'1、创始人拥有后台所有权限，若无特殊情况请勿更改。<br />
2、您可以添加新创始人，删除和修改其他创始人信息。',
		'manager_m'=>'创始人管理',
		'manager_add'=>'添加创始人',
		'manager_info1'=>'<br />3、如不需要更改密码，“新密码”、“确认密码” 请留空。',
		'manager_edit'=>'编辑创始人',
	),
	'ystats'	=> array(
		'ystats_cls_config' => '基本设置',
		'ystats_cls_report' => '数据报告',
		'ystats_config' => '统计说明',
		'ystats_yh_info_1' => '雅虎统计是一款第三方免费网站流量统计分析系统<br />
			通过统计分析大量数据, 结合网络营销,为您提供运营, 广告投放, 推广等决策依据<br />
			用户包括个人站长, 个人博主, 网站管理者, 第三方统计等<br />',
		'ystats_yh_info_2' => '绑定雅虎帐号可以登录雅虎平台，查看更详细的数据报告，你还没有绑定雅虎帐号',
		'ystats_yh_info_3' => '你已经绑定雅虎帐号,现在就可以登录雅虎平台，查看更详细的数据报告',
		'ystats_yh_open' => '开启雅虎统计',
		'ystats_yh_ifopen' => '是否开启雅虎统计',
		'ystats_yh_style' => '统计标识<br />选择前台标识显示的样式，但可能会存在延时问题。',
		'ystats_yh_style_2' => '雅虎统计',
	),
	'diyoption'	=> array(
		'diyoption_guide'=>'常用选项定制',
		'diyoption_guide_readme'=>'注:最多定制15条',
	),
	'optimize'	=> array(
		'optimize_guide'=>'优化方案说明',	'optimize_info1'=>'负载优化：根据您的站点规模进行优化，您也可以在“查看设置”中自定义设置负载优化选项<br/>功能设置：根据您对功能的需求快速开启/关闭站点功能，您也可以在“查看设置”中自定义设置功能设置选项<br/>说明：选中任何一个负载优化和功能设置，在核心设置中的值都将改成该处所配置的值',
		'optimize_title1'=>'负载优化',
		'optimize_title2'=>'功能设置',
		'optimize_size_1'=>'小型站点：30分钟在线 < 1000',
		'optimize_size_2'=>"中型站点：30分钟在线 < 5000",
		'optimize_size_3'=>"大型站点：30分钟在线 > 5000",
		'optimize_define_set'=>"查看设置",
		'optimize_func_1'=>"简洁：关闭娱乐和部分影响效率的功能，适合追求高效率的站点",
		'optimize_func_2'=>'推荐：按照站点日常基本需求配置，效率与功能比较平衡',
		'optimize_func_3'=>'丰富：开启大部分功能，站点会员体验较好，负载较前两种配置要高一些',
		'optimize_down1'=>'以下设置是系统推荐',
		'optimize_down2'=>'使用的优化配置方案，您可以根据您的具体需求自定义设置',
		'optimize_type_2'=>'中型站点',
		'optimize_type_3'=>'小型站点',
		'optimize_info2'=>'定时打开与关闭站点搜索功能：<br />
	允许用户使用搜索功能的时间段，时间格式为 24小时制，管理员与总版主不受此限制<br>
	比如允许用户在8点到18点这段时间内使用搜索功能，可设置如下：<br>
	搜索开启于(点): 8 点 搜索关闭于(点): 18 点<br>
	支持跨越零点，如允许用户在每晚22:00 到 次日 10:00 可设置如下：<br>
	搜索开启于(点): 22 点 搜索关闭于(点): 10 点',
		'optimize_searchstart' => '搜索开启于(点):',
		'optimize_searchend' => '搜索关闭于(点):',
		'optimize_lp' => '进程优化:<br>建议15分钟在线1000人以上站点打开此选项',
		'optimize_obstart' => 'GZIP 压缩级别:<br>设置 GZIP 在输出时的压缩级别: 0=关闭GZIP功能，9=最大压缩比。<br>如果您已经在服务器上使用了mod_gzip 或者 mod_deflate，请设置为0关闭GZIP功能，否则强烈推荐使用级别 1。另外，此功能要求 ZLIB 库支持。<br />GZIP 压缩输出简介：使用 GZIP HTML 压缩输出给用户页面，这会减少带宽要求。此功能要求客户端浏览器的支持，以及 HTTP 1.1 兼容。它会产生服务器额外的性能开销。',
		'optimize_ifonlinetime' => '是否记录会员在线时间并在版块内显示',
		'optimize_refreshtime' => '刷新预防时间(多少秒间刷新被视为恶意刷新,设为0则不做限制)：',
		'optimize_onlinetime' => '在线用户时限（多少分钟内有动作视为在线）：',
		'optimize_maxresult' => '搜索查询的最大结果数：',
		'optimize_post_cvtimes' => '帖子中表情，动作以及 img，wmv，rm 等标签的最多转换次数<br>建议设置为10 - 20 之间，-1 为不限制',
		'optimize_attachnum' => '一次最多上传附件个数',
		'optimize_birth' => '首页显示今天生日会员：<br>如果选择“开启”，将在站点首页显示今天过生日的会员，会影响速度。',
		'optimize_indexonline' => '首页显示在线用户(影响速度)：',
		'optimize_showguest' => '首页显示在线游客(影响速度)：',
		'optimize_today' => '统计今日到访会员(大型站点建议关闭，影响速度)：',
		'optimize_maxpage'=>'主题列表最大显示页数:<br>主题列表中用户可以查看的最大页数，建议设置为 1000 －2500 之间，0 为不限制',
		'optimize_maxmember'=>'用户列表最大页数:<br>用户列表显示的总页数，建议为1000-2500。0或留空表示不限制。',
		'optimize_hithour' => '点击率延迟更新功能(小时)<br>（设置为0则不使用此功能,使用生成html功能将自动使用此功能）',
		'optimize_threadonline' => '版块内显示在线用户：',
		'optimize_colony' => '是否在帖子页面显示用户加入的群组',
		'optimize_customcredit' => '选择要在阅读帖子页面（read.php）显示的自定义积分',
		'optimize_ifwatermark' => '是否使用图片水印功能<br>将在站点上传的图片附件中加上您在下面设置的图片或文字水印<br />开启后请到版块设置里开启',
		'optimize_iffthumb' => '是否使用头像缩略图功能<br />站点上的头像，按照一定比例，缩略成一张清晰的图片',
		'optimize_wapifopen'=>'是否开启WAP功能<br>开启此功能允许用户通过手机访问站点，实现浏览、发帖、收发短消息等功能',
		'optimize_jsifopen'=>'是否开启 JS调用<br>此功能允许在您的网站首页或其他地方调用站点的内容<br>调用方式分为： 版块调用、公告调用、基本信息调用、会员排行调用、文章调用。',
		'optimize_ifsafecv'=>'安全问题功能<br />如果会员设置了安全问题，需要填写正确的答案才能登录站点，可提高密码安全性',
		'optimize_safegroup'=>'强制使用安全问题用户组设置<br />可以强制管理权限较高的用户组(管理员,总版主,版主)使用安全问题，可提高密码安全性',
		'optimize_htmifopen'=>'是否开启静态目录部署功能',
		'optimize_ipstates'=>'是否开启IP统计',
		'optimize_ads' => '是否允许用户使用宣传代码!',
		'optimize_ads_2'=>"需要注册",
		'optimize_ads_1'=>"勿需注册",
		'optimize_ads_0'=>"关闭",
		'optimize_imgwidth'=>"头像宽高范围",
		'optimize_iconwidth' => '最大宽度',
		'optimize_iconlen' => '最大高度',
		'optimize_upload' => '是否开启头像上传功能<br>此处为全局控制，此功能关闭则所有用户都不能使用头像上传功能',
		'optimize_columns'=>'是否开启左右分栏',
		'optimize_columns_0'=>'关闭',
		'optimize_columns_1'=>'开启，默认使用平板模式',
		'optimize_columns_2'=>'开启，默认使用分栏模式',
		'optimize_msgsound' => '是否开启新消息声音提示',
		'optimize_shield'=>'是否开启屏蔽禁言会员所有帖子',
		'optimize_tcheck'=>'是否开启发帖内容验证(开启该功能，会员将无法连续发表同一内容的主题)',
		'optimize_adminset'=>'是否开启副版主功能(开启该功能，第一版主有权任命和罢免其他版主)',
		'optimize_allowupload' => '是否使用附件上传功能',
		'optimize_replysendmail' => '用户文章被回复是否发送邮件：',
		'optimize_replysitemail'=>'用户文章被回复是否发送站内通知：',
		'optimize_pwcode' => '编辑器是否开启自定义代码功能：',
		'optimize_setform' => '编辑器是否开启帖子格式功能：',
		'optimize_autoimg' => '是否使用自动贴图',
		'optimize_menu'=>'弹出菜单显示<br /> 头部导航 (统计排行)<br /> 版块导航 (帖子列表、发帖页面)<br />个人信息 (帖子列表)',
		'optimize_menu_1'=>' 头部导航',
		'optimize_menu_2'=>' 版块导航',
		'optimize_menu_4'=>' 个人信息',
		'optimize_topped' => '总置顶, 分类置顶功能：<br>置顶3 为总置顶, 置顶2 为分类置顶, 置顶1 为本版块置顶',
		'optimize_ifwatermark' => '是否使用图片水印功能<br>将在站点上传的图片附件中加上您在下面设置的图片或文字水印<br />开启后请到版块设置里开启',
		'optimize_iffthumb' => '是否使用头像缩略图功能<br />站点上的头像，按照一定比例，缩略成一张清晰的图片',
		'optimize_ifathumb' => '是否使用附件缩略图功能<br />站点上的图片附件，按照一定比例，缩略成一张清晰的图片',
		'optimize_ifselfshare' => '是否开启自助友情链接<br />会员可在前台自助申请友情链接（每个会员只能申请一次），管理员审核通过后在前台显示',
		'optimize_hello'=>' 保存并应用',
		'optimize_recovery'=>' 恢复默认值',
	),
	'maketemplate'	=> array(
		'maketemplate_center'		=> '模块生成',
		'maketemplate_invoke'=> '调用代码:',
		'maketemplate_cycle'=> '循环模块',
		'maketemplate_name'=> '模块名称:',
		'maketemplate_norepeat'=> '(不可重复)',
		'maketemplate_creat'=> '创建模块',
		'maketemplate_copy'=> '请将下面代码复制到模板里面',
		'maketemplate_set'=> '设置模块',
		'maketemplate_setcycle'=> '设置循环的版块：(按住ctrl键可多选)',
		'maketemplate_invokenum'=> '调用个数：',
		'maketemplate_updatetime'=> '缓存更新时间：',
	),

	'area_selecttpl' => array(
		'seletetpl_center'=>'模板中心',
		'seletetpl_indexselect'=>'首页模板选择',
		'seletetpl_default'=>'(默认)',
		'seletetpl_thistpl'=>'当前模板',
		'seletetpl_setthistpl'=>'设置为当前模板',
		'seletetpl_cateselect'=>'频道模板选择',
	),
	'area_tplcontent' => array(
		'tplcontent_contentmanage'=>'模块内容管理',
		'tplcontent_selectpage'=>'选择管理页面',
		'tplcontent_editinvoke'=>'设置模块属性',
		'tplcontent_editpagetpl'=>'管理本页面模块内容',
		'tplcontent_editblockcontent'=>'管理模块内容',
		'tplcontent_blockdescrp'=>'模块管理:',
		'tplcontent_updatecache'=>'更新页面缓存',
		'tplcontent_seletctpl'=>'选择模块',
		'tplcontent_manage'=>'模块管理',
		'tplcontent_inputtid'=>'请输入要调用的帖子tid:',
		'tplcontent_add'=>'添加',
		'tplcontent_helpself'=>'自定义内容',
	),
	'area_edittpl'	=> array(
		'edittpl_templatemanage'=>'本站模板管理',
		'edittpl_gotplcenter'=>'去模板中心',
		'edittpl_everpagetpl'=>'本站各频道模板',
		'edittpl_selectothertpl'=>'选择其他模板',
	),

	'o_global'		=> array(
		'global_title' => '圈子核心设置',
		'global_invite' => '是否开启好友邀请',
		'global_browse' => '随便看看模块开启：',
		'global_indexset' => '未登录状态圈子首页模块开启：',
	),

	'app_diary'		=> array(
		'diary_set_title'	=> '日志基本设置',
		'diary_dopen' => '是否开启日志功能：',
		'diary_gdcheck' => '是否开启发表日志认证码：',
		'diary_qcheck' => '是否开启验证问题：',
		'diary_creategroup' => '允许发表日志的用户组：全不选为任何用户组可发日志',
		'diary_limit' => '每天最多允许发表多少篇日志：设置为0不限制',
		'diary_pertime' => '日志灌水预防：多少秒间隔内不能发日志,设为0则不做限制',
		'diary_shownum' => '日志列表页日志内容显示字节：0表示全篇显示',
		'diary_uploadsize' => '上传附件允许后缀和最大尺寸：[KB]0为不限制',
		'diary_uploadsize_1' => '后缀名',
		'diary_uploadsize_2' => '最大尺寸',
		'diary_attachdir' => '附件保存方式：如果使用非默认的保存方式，请确认 mkdir() 函数可正常使用，否则设置后新上传的附件无法保存，更改不影响已上传附件。',
		'diary_attachdir_0' => '全部存入同一目录(默认)',
		'diary_attachdir_1' => '按类型存入不同目录',
		'diary_attachdir_2' => '按月份存入不同目录',
		'diary_attachdir_3' => '按天存入不同目录',
		'diary_jifenset'	=> '日志积分奖惩设置',
		'diary_jifensetwarning' => '注：威望积分设置支持1位小数点，其他积分只允许整数！',
		'diary_jifenliutong' => '日志积分流通记录',
		'diary_jifenliutonghelf' => '此功能可以详细记录某种积分的流通情况，帮助站长更加清晰地掌握站点的积分状况！',

		'action=cp'	=> array(
			'name'=>'日志管理',
			'diary_cp_title2' => '日志搜索',
			'diary_cp_group' => '用户组：',
			'diary_cp_au' => '作 者：(多个作者用","分隔)',
			'diary_cp_keyword' => '关键字：(多个关键字用","分隔)',
			'diary_cp_preg' => '可使用通配符 "*"',
			'diary_cp_posttime' => '发表日期：(格式 yyyy-mm-dd)',
			'diary_cp_lessview' => '浏览人数小于：',
			'diary_cp_diary' => '的日志',
			'diary_cp_lessreply' => '回复人数小于：',
			'diary_cp_tcounts' => '内容大于：',
			'diary_cp_counts' => '内容小于：',
			'diary_cp_bit' => '字节',
			'diary_orderby' => '排序：',
		),
	),
	'app_groups'		=> array(
		'groups_setting' => '基本设置',
		'groups_cache' => '更新缓存',
		'groups_open' => '是否开启群组：',
		'groups_remove' => '是否允许创始人解散群组：',
		'groups_newcolony' => '是否允许注册新群组：',
		'groups_gdcheck' => '是否开启创建群组认证码：',
		'groups_p_gdcheck' => '是否开启发表新主题认证码：',
		'groups_qcheck' => '是否开启创建群组验证问题：',
		'groups_p_qcheck' => '是否开启发表新主题验证问题：',
		'groups_moneytype' => '选择群组的消费积分：',
		'groups_moneytypeinfo' => '（一旦设置，请勿随意更改）',
		'groups_createmoney' => '创建一个群组所需：',
		'groups_allowcreate' => '每个会员最多能创建群组的个数：',
		'groups_none' => '（0 或 留空 表示没限制）',
		'groups_joinmoney' => '会员加入群组至少需交纳的数：',
		'groups_allowjoin' => '每个会员最多能加入群组的个数：',
		'groups_memberfull' => '群组容纳会员最大值：',
		'groups_imgsize' => '群组标志图片最大尺寸：',
		'groups_imgsize_info' => '（单位k，0 或 留空 则按论坛模式配置）',
		'groups_img' => '群组标志图片宽高范围：',
		'groups_imgwidth' => '宽',
		'groups_imgheight' => '高',
		'groups_creategroup' => '允许创建群组的用户组：（全不选则允许所有用户组创建）',
		'diary_jifenset'	=> '群组积分奖惩设置',
		'diary_jifensetwarning' => '注：威望积分设置支持1位小数点，其他积分只允许整数！',
		'diary_jifenliutong' => '群组积分流通记录',
		'diary_jifenliutonghelf' => '此功能可以详细记录某种积分的流通情况，帮助站长更加清晰地掌握站点的积分状况！',
		'action=class'=>array(
			'name' => '分类管理',
			'groups_cname' => '分类名称',
			'groups_nums' => '群组个数',
			'groups_addcname' => '添加分类',
		),
		'action=colony'	=> array(
			'name' => '群组管理',
		),
		'action=argument'=>array(
			'name' => '帖子管理',
			'groups_cid' => '群组分类:',
			'groups_allcid' => '不限制',
			'groups_authorall' => '作 者: (可使用通配符 "*")',
			'groups_ckauthor' => '精确匹配',
			'groups_keyall' => '关键字: (可使用通配符 "*")',
			'groups_postdate_s' => '发表日期: (格式 yyyy-mm-dd)',
			'groups_admin' => '管理选项:',
			'groups_orderby' => '排序:',
			'groups_authorid' => '帖子作者',
			'groups_lines' => '每页显示行数:',
		),
		'action=cache'=>array(
			'name'=>'缓存更新',
			'groups_cache_title' => '缓存更新',
			'groups_newsetting' => '更新分类管理',
			'groups_update_cl' => '更新朋友圈分类',
			'groups_delcolony' => '清除没有分类的朋友圈( 此将删除关联没有分类的朋友圈所有东西，删除后不能再恢复，请确定若只是修改朋友圈分类，请到朋友圈管理处修改分类 )',
		),
	),
	'app_photos'	=> array(
		'photos_setting' => '相册设置',
		'photos_photos' => '相片管理',
		'photos_set_title' => '相册基本设置',
		'photos_phopen' => '是否开启相册功能：',
		'photos_gdcheck' => '是否开启验证码：',
		'photos_creategroup' => '允许创建相册的用户组：<br />全不选为任何用户组可创建相册',
		'photos_qcheck' => '是否开启验证问题：',
		'photos_camoney' => '创建一个相册所需花费{$credit->cType[$o_moneytype]}：',
		'photos_nums' => '每个群组最多可以拥有的相册数：',
		'photos_nums2' => '每个会员可以创建的相册数：',
		'photos_maxphotonum' => '每个相册最多可容纳的相片数：',
		'photos_maxphotonuminfo' => '（不适合太大，建议值：20-30）',
		'photos_mkdir' => '相册分目录建立标准：',
		'photos_mkdir_1' => '按月存入不同目录',
		'photos_mkdir_2' => '按日存入不同目录',
		'photos_mkdir_3' => '按群组ID存入不同目录',
		'photos_maxfilesize' => '上传单张图片的最大尺寸：（单位k）',
		'diary_jifenset'	=> '相册积分奖惩设置',
		'diary_jifensetwarning' => '注：威望积分设置支持1位小数点，其他积分只允许整数！',
		'diary_jifenliutong' => '相册积分流通记录',
		'diary_jifenliutonghelf' => '此功能可以详细记录某种积分的流通情况，帮助站长更加清晰地掌握站点的积分状况！',
		'action=albums'=> array(
			'name' => '相册管理',
			'photos_s_aname' => '相册名称（可使用通配符“*”）',
			'photos_s_owner' => '作者名称（可使用通配符“*”）',
			'photos_s_lasttime' => '最后更新日期',
		),
		'action=photos'=>array(
			'name'=>'相片管理',
			'photos_searchs' => '相片搜索',
			'photos_s_aname2' => '所属相册名称（可使用通配符“*”）',
			'photos_s_aid' => '所属相册ID',
			'photos_s_pintro' => '描述（可使用通配符“*”）',
			'photos_s_uptime' => '上传日期',
			'photos_default' => '排序',
		),
	),
	'app_write'		=> array(
		'diary_jifenset'	=> '记录积分奖惩设置',
		'diary_jifensetwarning' => '注：威望积分设置支持1位小数点，其他积分只允许整数！',
		'diary_jifenliutong' => '记录积分流通记录',
		'diary_jifenliutonghelf' => '此功能可以详细记录某种积分的流通情况，帮助站长更加清晰地掌握站点的积分状况！',
		'action=writes'	=> array(
			'name'=>'记录管理',
			'write_title' => '记录搜索',
			'write_content' => '记录内容（可使用通配符“*”）',
			'write_username' => '作者名称（可使用通配符“*”）',
			'write_list' => '记录列表',
			'write_from' => '来源',
			'write_c_num' => '评论数',
			'write_web' => '网页',
			'write_signature' => '个性签名',
			'write_other' => '其他',
			'write_confirm' => '确定要删除所选记录吗？',
		),
	),
	'app_share'		=> array(
		'share_setting' => '分享设置',
		'share_share' => '分享管理',
		'share_set_title' => '分享基本设置',
		'share_open' => '是否开启分享功能：',
		'share_creategroup' => '允许分享的用户组：<br />全不选为任何用户组可发分享',
		'share_gdcheck' => '是否开启验证码：',
		'share_qcheck' => '是否开启验证问题：',
		'diary_jifenset'	=> '分享积分奖惩设置',
		'diary_jifensetwarning' => '注：威望积分设置支持1位小数点，其他积分只允许整数！',
		'diary_jifenliutong' => '分享积分流通记录',
		'diary_jifenliutonghelf' => '此功能可以详细记录某种积分的流通情况，帮助站长更加清晰地掌握站点的积分状况！',
		'action=share'=>array(
			'name'=>'分享管理',
			'share_share_title' => '分享搜索',
			'share_type' => '分享类型',
			'share_type_all' => '全部',
			'share_type_user' => '用户',
			'share_type_diary' => '日志',
			'share_type_photo' => '照片',
			'share_type_album' => '相册',
			'share_type_group' => '群组',
			'share_type_video' => '视频',
			'share_type_music' => '音乐',
			'share_type_web' => '网页',
			'share_ifhidden' => '是否私有',
			'share_ifhidden_all' => '全部',
			'share_ifhidden_0' => '公开',
			'share_ifhidden_1' => '私有',
			'share_username' => '作者名称（可使用通配符“*”）',
			'share_postdate_s' => '分享日期',
			'share_list' => '分享列表',
			'share_c_num' => '评论数',
			'share_confirm' => '确定要删除所选分享吗？',
		),
	),
	'app_hot'		=> array(
		'hot_base_set' => '基本设置',
		'hot_sort_type' => '排行类型设置',
		'hot_if_open' => '是否开启热榜：',
		'hot_view_purview' => '浏览权限：',
		'hot_purview_descrip' => '（勾选允许浏览的用户组，全不选表示全开放）',
	),

	'o_comments'		=> array(
		'comments_title' => '评论搜索',
		'comments_type' => '评论类型',
		'comments_content' => '评论内容（可使用通配符“*”）',
		'comments_usernane' => '作者名称（可使用通配符“*”）',
		'comments_posttime' => '发表时间 ：',
		'comments_list' => '评论列表',
		'comments_des' => '内容',
		'comments_ch_type' => '所属类型',
	),
	'app'				=> array(
		'app_acount'	=> 'APP平台帐号',
		'app_self_acount'	=> '您好，您在APP平台的帐号为',
		'app_reg_acount'	=> '您好，您在APP平台未绑定贵站信息，请立即 注册或绑定',
		'app_version'	=> '版本检测',
		'app_descript'	=> '当前PHPWind扩展平台用户端最新版本 我已经安装的版本是',
		'app_fsock_error'	=> '服务器不支持fsockopen，APP用户端无法使用！',

		'app_edit_key'	=> '修改密钥',
		'action=app'	=> array(
			'name'	=> '应用列表',
			'app_name'	=> '应用名称',
			'app_base'	=> '基础应用',
			'app_disanfang'	=> '第三方在线应用',
			'app_descript'	=> 'app应用简介 app应用是由 PHPWind 提供的程序扩展服务。站长可自主选择是否开启，并且可针对每个应用设置是否启用。',
			'app_explain'	=> '1、当站点应用使用异常时，你可以使用数据更新操作将站点信息更新到app应用平台。<br />
	2、关闭应用之后，所有用户应用都将无法使用。',
			'app_version'	=> '版本检测',
		),
		'action=blooming'	=> array(
			'name'	=> '帖子交换',
			'app_bloom_descrip'	=> '1.选择常用分类：在前台推送帖子的时候，将优先展示选中的分类，请根据您的需求选择。<br />
	2.点击获取最新分类：当PHPWind.com平台，有分类更新时，点击即可获取最新分类信息。<br />
	3.使用用户组：控制用户组使用帖子推送的权限。'
		),
	),
	'msphinx'			=> array(
		'msphinx_config'	=> 'Sphinx全文索引配置',
		'msphinx_descrip'	=> '介绍说明',
		'msphinx_descrip_info'	=> 'Sphinx是一个基于SQL的全文检索引擎，可以结合MySQL,PostgreSQL做全文搜索，它可以提供比数据库本身更专业的搜索功能，使得应用程序更容易实现专业化的全文检索。Sphinx特别为一些脚本语言设计搜索API接口，如PHP,Python,Perl,Ruby等，同时为MySQL也设计了一个存储引擎插件。',
		'msphinx_admin'	=> '全文索引管理',
		'msphinx_ifopen'	=> '是否开启全文索引',
	),
	'mmemcache'			=> array(
		'mmemcache_config'	=> 'Memcache 缓存配置',
		'mmemcache_descrip_info'	=> 'memcached是以LiveJournal旗下Danga Interactive公司的Brad Fitzpatric为首开发的一款开源软件。现在已成为从多服务中提高Web应用扩展性的重要因素。许多Web应用都将数据保存到RDBMS中,应用服务器从中读取数据并在浏览器中显示。但随着数据量的增大、访问的集中，就会出现RDBMS的负担加重、数据库响应恶化、网站显示延迟等重大影响。memcached是高性能的分布式内存缓存服务器。一般的使用目的是，通过缓存数据库查询结果，减少数据库访问次数，以提高动态Web应用的速度、提高可扩展性。Memcache官方网站：',
		'mmemcache_ifopen'	=> '是否开启Memcache',
	),
	'ucset'				=> array(
		'ucset_info'	=> '此处用于设置多个系统间的用户信息共享，并实现各系统间用户资料、操作等的同步。独立系统—表示系统没有跟其他系统共享用户信息；<br />用户中心服务端—表示系统为用户中心主站，设置过程中其本身的数据将不受影响；设置完成后，需要到《应用管理》中添加附站信息；用户中心客户端—表示系统为用户中心附站，设置完成后，其用户信息将被主站覆盖（设置需谨慎）',
		'ucset_set_for'	=> '将本系统作为：',
		'ucset_set_for_single'	=> '独立系统',
		'ucset_set_for_server'	=> '用户中心服务端',
		'ucset_set_for_client'	=> '用户中心客户端（用户中心的一个子应用）',
		'ucset_id'	=> '本应用id',
		'ucset_key'	=> '本应用密钥',
		'ucset_server_ip'	=> '服务端数据库主机名 或 IP 地址',
		'ucset_server_sql_username'	=> '服务端数据库用户名',
		'ucset_server_sql_keyword'	=> '服务端数据库密码',
		'ucset_sercer_sql_name'	=> '服务端数据库名',
		'ucset_sercer_sql_prefix'	=> '服务端数据库表前缀',
		'ucset_sercer_sql_language'	=> '服务端数据库表字符编码',
	),
);
?>